
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Assets.Scripts
{

    //  public enum Languages
    //  {
    //      English,
    //      Russian,
    //  }

    public class UiLang : MonoBehaviour
    {

        //      public static readonly Dictionary<int, SystemLanguage>[] Lang2SystemLang = {
        //          new Dictionary<Languages, SystemLanguage>
        //          {
        //              {"EditorLayer.ActiveColor", "Active color"},
        //          }

        public static readonly Dictionary<string, string>[] Dictionaries = {
            new Dictionary<string, string>
            {
                {"EditorLayer.ActiveColor", "Active color"},
                {"EditorLayer.Details", "Elements"},

                {"Menu.Menu", "Menu"},
                {"Menu.NewScene", "New scene"},
                {"Menu.Save", "Save..."},
                {"Menu.Load", "Load..."},
                {"Menu.Export", "Export..."},
                {"Menu.SceneInfo", "Scene Info"},
                {"Menu.ModelsSets", "Models"},
                {"Menu.Help", "Help"},
                {"Menu.Exit", "Exit"},

                {"ModeSwitcher.Editor", "Editor mode"},
                {"ModeSwitcher.Instructions", "Instructions mode"},

                {"SceneInfoLayer.Copy", "Copy"},
                {"SceneInfoLayer.Height", "Height:"},
                {"SceneInfoLayer.Length", "Length:"},
                {"SceneInfoLayer.Width", "Width:"},
                {"SceneInfoLayer.Weight", "Weight:"},
                {"SceneInfoLayer.TotalDetails", "Total details:"},
                {"SceneInfoLayer.cm", "cm"},
                {"SceneInfoLayer.gram", "g"},

                {"SceneInfoLayer.Black", "Black"},
                {"SceneInfoLayer.Blue", "Blue"},
                {"SceneInfoLayer.Brown", "Brown"},
                {"SceneInfoLayer.Gray", "Gray"},
                {"SceneInfoLayer.Green", "Green"},
                {"SceneInfoLayer.Red", "Red"},
                {"SceneInfoLayer.White", "White"},
                {"SceneInfoLayer.Yellow", "Yellow"},

                {"SceneInfoLayer.BraceLineX2", "Brace Line (2x1): "},
                {"SceneInfoLayer.BraceLineX3", "Brace Line (3x1): "},
                {"SceneInfoLayer.BraceSquareX2", "Brace Square (2x1): "},
                {"SceneInfoLayer.BraceSquareX3", "Brace Square (3x1): "},
                {"SceneInfoLayer.Lego1x1", "Lego 1x1: "},
                {"SceneInfoLayer.Lego2x1", "Lego 2x1: "},
                {"SceneInfoLayer.Roll", "Roll: "},
                {"SceneInfoLayer.RailX2", "Rail: "},

                {"SceneInfoLayer.Axle1.0", "Axle 1.0: "},
                {"SceneInfoLayer.Axle2.0", "Axle 2.0: "},
                {"SceneInfoLayer.Axle2.5", "Axle 2.5: "},
                {"SceneInfoLayer.Axle3.0", "Axle 3.0: "},
                {"SceneInfoLayer.Axle3.5", "Axle 3.5: "},
                {"SceneInfoLayer.Axle8.0", "Axle 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Bevel Gear: "},
                {"SceneInfoLayer.AxleCoupling", "Coupling: "},
                {"SceneInfoLayer.AxleHub3x1", "Hub (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Hub (5x1): "},
                {"SceneInfoLayer.AxleTip", "Axle Tip: "},
                {"SceneInfoLayer.AxleWasher", "Washer: "},
                {"SceneInfoLayer.AxleWasherToothed", "Toothed Washer: "},
                {"SceneInfoLayer.AxleWheelBig", "Big Wheel: "},
                {"SceneInfoLayer.AxleWheelSmall", "Small Wheel: "},

                {"FileSelectionDialogLayer.SelectFile", "Select file..."},
                {"FileSelectionDialogLayer.EnterName", "Enter name..."},
                {"FileSelectionDialogLayer.Up", "Up"},
                {"FileSelectionDialogLayer.Downloads", "Downloads"},
                {"FileSelectionDialogLayer.Save", "Save"},
                {"FileSelectionDialogLayer.Cancel", "Cancel"},

                {"TutorialLayer.Next", "Next"},
                {"TutorialLayer.Welcome", "Welcome to\nFanclastic 3D Designer!\n\nThis program helps you to build Fanclastic models, view assembly instructions and create your own."},
                {"TutorialLayer.DetailsHint", "To add an element to the scene drag a corresponding icon from the elements' panel to the scene."},
                {"TutorialLayer.SetFocusHint", "To change camera anchor point click on the focus setting button and then on any element or spot on the scene."},
                {"TutorialLayer.ChangeColorHint", "Use the color select button to set a color for selected elements."},
                {"TutorialLayer.RotateHint", "To rotate selected elements use rotation buttons. Each button rotates elements around a drawn axis of a corresponding color."},
                {"TutorialLayer.DeleteHint", "Use this button to delete selected elements from the scene."},
                {"TutorialLayer.ZoomHint.Base", "Use {0} to zoom in and out the camera."},
                {"TutorialLayer.ZoomHint.Wheel", "mouse wheel"},
                {"TutorialLayer.ZoomHint.Pinch", "pinch"},
                {"TutorialLayer.LinkedSelection", "Click on an element and hold to select all linked parts."},

                {"ModelsSetsLayer.SetsNames.ModelsSets", "Models sets"},

                {"ModelsSetsLayer.SetsNames.KBigFigures", "Big Figures"},
                {"ModelsSetsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
                {"ModelsSetsLayer.SetsNames.Architectics", "Architectics"},
                {"ModelsSetsLayer.SetsNames.Geometrics", "Geometrics"},
                {"ModelsSetsLayer.SetsNames.Blasterology", "Blasterology"},
                {"ModelsSetsLayer.SetsNames.Militarics", "Militarics"},
                {"ModelsSetsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
                {"ModelsSetsLayer.SetsNames.Monsterology", "Monsterology"},
                {"ModelsSetsLayer.SetsNames.Robotology", "Robotology"},
                {"ModelsSetsLayer.SetsNames.Geometry", "Geometry"},
                {"ModelsSetsLayer.SetsNames.Architecture", "Architecture"},
                {"ModelsSetsLayer.SetsNames.Spaceships", "Spaceships"},
                {"ModelsSetsLayer.SetsNames.Playground", "Playground"},
                {"ModelsSetsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
                {"ModelsSetsLayer.SetsNames.Marine", "Marine"},
                {"ModelsSetsLayer.SetsNames.Aircraft", "Aircraft"},
                {"ModelsSetsLayer.SetsNames.Space", "Space"},
                {"ModelsSetsLayer.SetsNames.Mix", "Mix"},
                {"ModelsSetsLayer.SetsNames.Animals", "Animals"},
                {"ModelsSetsLayer.SetsNames.Flowers", "Flowers"},
                {"ModelsSetsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
                {"ModelsSetsLayer.SetsNames.BirdLama", "Bird-Lama"},
                {"ModelsSetsLayer.SetsNames.PlaneShip", "Plane-Ship"},
                {"ModelsSetsLayer.SetsNames.Butterflies", "Butterflies"},
                {"ModelsSetsLayer.SetsNames.Masks", "Masks"},
                {"ModelsSetsLayer.SetsNames.Racing", "Racing"},
                {"ModelsSetsLayer.SetsNames.RallyRade", "Rally Rade"},
                {"ModelsSetsLayer.SetsNames.Kids200", "Kids 200"},
                {"ModelsSetsLayer.SetsNames.Kids100", "Kids 100"},
                {"ModelsSetsLayer.SetsNames.Kids40", "Kids 40"},

                {"ModelsSetsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
                {"ModelsSetsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
                {"ModelsSetsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
                {"ModelsSetsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
                {"ModelsSetsLayer.ModelsNames.KingsCastle", "King's Castle"},
                {"ModelsSetsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
                {"ModelsSetsLayer.ModelsNames.SpaceLight", "Space Light"},
                {"ModelsSetsLayer.ModelsNames.Cube", "Cube"},
                {"ModelsSetsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
                {"ModelsSetsLayer.ModelsNames.Fractal", "Fractal"},
                {"ModelsSetsLayer.ModelsNames.Globe", "Globe"},
                {"ModelsSetsLayer.ModelsNames.Lattice", "Lattice"},
                {"ModelsSetsLayer.ModelsNames.Pyramid", "Pyramid"},
                {"ModelsSetsLayer.ModelsNames.Sphere", "Sphere"},
                {"ModelsSetsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
                {"ModelsSetsLayer.ModelsNames.Megablaster", "Megablaster"},
                {"ModelsSetsLayer.ModelsNames.Miniblaster", "Miniblaster"},
                {"ModelsSetsLayer.ModelsNames.Parablaster", "Parablaster"},
                {"ModelsSetsLayer.ModelsNames.Fighter", "Fighter"},
                {"ModelsSetsLayer.ModelsNames.Helicopter", "Helicopter"},
                {"ModelsSetsLayer.ModelsNames.Submarine", "Submarine"},
                {"ModelsSetsLayer.ModelsNames.Tank", "Tank"},
                {"ModelsSetsLayer.ModelsNames.Dachshund", "Dachshund"},
                {"ModelsSetsLayer.ModelsNames.Fawn", "Fawn"},
                {"ModelsSetsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
                {"ModelsSetsLayer.ModelsNames.SaurKing", "Saur King"},
                {"ModelsSetsLayer.ModelsNames.Tortilla", "Tortilla"},
                {"ModelsSetsLayer.ModelsNames.Triceratops", "Triceratops"},
                {"ModelsSetsLayer.ModelsNames.Bossmonster", "Bossmonster"},
                {"ModelsSetsLayer.ModelsNames.Cyclops", "Cyclops"},
                {"ModelsSetsLayer.ModelsNames.Monster", "Monster"},
                {"ModelsSetsLayer.ModelsNames.Radiomonster", "Radiomonster"},
                {"ModelsSetsLayer.ModelsNames.Smartmonster", "Smartmonster"},
                {"ModelsSetsLayer.ModelsNames.Stereomonster", "Stereomonster"},
                {"ModelsSetsLayer.ModelsNames.Telemonster", "Telemonster"},
                {"ModelsSetsLayer.ModelsNames.Threeclopes", "Threeclopes"},
                {"ModelsSetsLayer.ModelsNames.RobotAndroid", "Robot 1"},
                {"ModelsSetsLayer.ModelsNames.RobotTransformer", "Robot 4"},
                {"ModelsSetsLayer.ModelsNames.RobotFerreous", "Robot 2"},
                {"ModelsSetsLayer.ModelsNames.RobotQuadric", "Robot 3"},
                {"ModelsSetsLayer.ModelsNames.RollerRobot", "Roller Robot"},
                {"ModelsSetsLayer.ModelsNames.Crystal", "Crystal"},
                {"ModelsSetsLayer.ModelsNames.Hexanom", "Hexanom"},
                {"ModelsSetsLayer.ModelsNames.Neutron", "Neutron"},
                {"ModelsSetsLayer.ModelsNames.Prism", "Prism"},
                {"ModelsSetsLayer.ModelsNames.Spring", "Spring"},
                {"ModelsSetsLayer.ModelsNames.VectorTower", "Vector Tower"},
                {"ModelsSetsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
                {"ModelsSetsLayer.ModelsNames.FortRoyal", "Fort Royal"},
                {"ModelsSetsLayer.ModelsNames.Skyscraper", "Skyscraper"},
                {"ModelsSetsLayer.ModelsNames.Destroyer", "Destroyer"},
                {"ModelsSetsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
                {"ModelsSetsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
                {"ModelsSetsLayer.ModelsNames.SpacePike", "Space Pike"},
                {"ModelsSetsLayer.ModelsNames.TSpace", "TSpace"},
                {"ModelsSetsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
                {"ModelsSetsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
                {"ModelsSetsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
                {"ModelsSetsLayer.ModelsNames.Seesaw", "Seesaw"},
                {"ModelsSetsLayer.ModelsNames.Slide", "Slide"},
                {"ModelsSetsLayer.ModelsNames.Swing", "Swing"},
                {"ModelsSetsLayer.ModelsNames.Frusaur", "Frusaur"},
                {"ModelsSetsLayer.ModelsNames.Catamaran", "Catamaran"},
                {"ModelsSetsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
                {"ModelsSetsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
                {"ModelsSetsLayer.ModelsNames.Airplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.ControlTower", "Control Tower"},
                {"ModelsSetsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
                {"ModelsSetsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
                {"ModelsSetsLayer.ModelsNames.SpaceRadar", "Space Radar"},
                {"ModelsSetsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
                {"ModelsSetsLayer.ModelsNames.Babycopter", "Babycopter"},
                {"ModelsSetsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
                {"ModelsSetsLayer.ModelsNames.Giraffe", "Giraffe"},
                {"ModelsSetsLayer.ModelsNames.HandBridge", "Hand-bridge"},
                {"ModelsSetsLayer.ModelsNames.Plane", "Plane"},
                {"ModelsSetsLayer.ModelsNames.Robot", "Robot"},
                {"ModelsSetsLayer.ModelsNames.Tower", "Tower"},
                {"ModelsSetsLayer.ModelsNames.Umberflower", "Umberflower"},
                {"ModelsSetsLayer.ModelsNames.BabyPanda", "Baby Panda"},
                {"ModelsSetsLayer.ModelsNames.Doggie", "Doggie"},
                {"ModelsSetsLayer.ModelsNames.Lamb", "Lamb"},
                {"ModelsSetsLayer.ModelsNames.Dandelion", "Dandelion"},
                {"ModelsSetsLayer.ModelsNames.Lily", "Lily"},
                {"ModelsSetsLayer.ModelsNames.BabyDeer", "Baby Deer"},
                {"ModelsSetsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
                {"ModelsSetsLayer.ModelsNames.Birdy", "Birdy"},
                {"ModelsSetsLayer.ModelsNames.Lama", "Lama"},
                {"ModelsSetsLayer.ModelsNames.LittleShip", "Little Ship"},
                {"ModelsSetsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
                {"ModelsSetsLayer.ModelsNames.Swallowtail", "Swallowtail"},
                {"ModelsSetsLayer.ModelsNames.Moustashed", "Moustashed"},
                {"ModelsSetsLayer.ModelsNames.QuadBike", "Quad Bike"},
                {"ModelsSetsLayer.ModelsNames.RaceCar", "Race Car"},
                {"ModelsSetsLayer.ModelsNames.Buggy", "Buggy"},
                {"ModelsSetsLayer.ModelsNames.Motocycle", "Motocycle"},
                {"ModelsSetsLayer.ModelsNames.Tricycle", "Tricycle"},
                {"ModelsSetsLayer.ModelsNames.KidsAirplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.KidsChair", "Chair"},
                {"ModelsSetsLayer.ModelsNames.KidsDragonfly", "Dragonfly"},
                {"ModelsSetsLayer.ModelsNames.KidsLodge", "Lodge"},
                {"ModelsSetsLayer.ModelsNames.KidsMan", "Little Man"},
                {"ModelsSetsLayer.ModelsNames.KidsPuppy", "Puppy"},
                {"ModelsSetsLayer.ModelsNames.KidsSpider", "Spider"},
                {"ModelsSetsLayer.ModelsNames.KidsTree", "Tree"},
                {"ModelsSetsLayer.ModelsNames.KidsTruck", "Truck"},
                {"ModelsSetsLayer.ModelsNames.KidsTruckCrane", "Truck Crane"},
                {"ModelsSetsLayer.ModelsNames.KidsVase", "Vase"},
                {"ModelsSetsLayer.ModelsNames.KidsBench", "Bench"},
                {"ModelsSetsLayer.ModelsNames.KidsTable", "Table"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 (3)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 (4)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 (5)"},
                {"ModelsSetsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
                {"ModelsSetsLayer.ModelsNames.Unbreakable", "Unbreakable"},
                {"ModelsSetsLayer.ModelsNames.Logo", "Logo"},
            },
            new Dictionary<string, string>
            {
                {"EditorLayer.ActiveColor", "Активный цвет"},
                {"EditorLayer.Details", "Детали"},

                {"Menu.Menu", "Меню"},
                {"Menu.NewScene", "Новая сцена"},
                {"Menu.Save", "Сохранить..."},
                {"Menu.Load", "Загрузить..."},
                {"Menu.Export", "Экспорт..."},
                {"Menu.SceneInfo", "Инфо сцены"},
                {"Menu.ModelsSets", "Модели"},
                {"Menu.Help", "Помощь"},
                {"Menu.Exit", "Выход"},

                {"ModeSwitcher.Editor", "Редактор"},
                {"ModeSwitcher.Instructions", "Инструкции"},

                {"SceneInfoLayer.Copy", "Копир."},
                {"SceneInfoLayer.Height", "Высота:"},
                {"SceneInfoLayer.Length", "Длина:"},
                {"SceneInfoLayer.Width", "Ширина:"},
                {"SceneInfoLayer.Weight", "Вес:"},
                {"SceneInfoLayer.TotalDetails", "Всего деталей:"},
                {"SceneInfoLayer.cm", "см"},
                {"SceneInfoLayer.gram", "г"},

                {"SceneInfoLayer.Black", "Черный"},
                {"SceneInfoLayer.Blue", "Синий"},
                {"SceneInfoLayer.Brown", "Коричневый"},
                {"SceneInfoLayer.Gray", "Серый"},
                {"SceneInfoLayer.Green", "Зеленый"},
                {"SceneInfoLayer.Red", "Красный"},
                {"SceneInfoLayer.White", "Белый"},
                {"SceneInfoLayer.Yellow", "Желтый"},

                {"SceneInfoLayer.Axle1.0", "Ось 1.0: "},
                {"SceneInfoLayer.Axle2.0", "Ось 2.0: "},
                {"SceneInfoLayer.Axle2.5", "Ось 2.5: "},
                {"SceneInfoLayer.Axle3.0", "Ось 3.0: "},
                {"SceneInfoLayer.Axle3.5", "Ось 3.5: "},
                {"SceneInfoLayer.Axle8.0", "Ось 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Конусная шестеренка: "},
                {"SceneInfoLayer.AxleCoupling", "Муфта: "},
                {"SceneInfoLayer.AxleHub3x1", "Ступица (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Ступица (5x1): "},
                {"SceneInfoLayer.AxleTip", "Осевой наконечник: "},
                {"SceneInfoLayer.AxleWasher", "Шайба: "},
                {"SceneInfoLayer.AxleWasherToothed", "Зубчатая шайба: "},
                {"SceneInfoLayer.AxleWheelBig", "Большое колесо: "},
                {"SceneInfoLayer.AxleWheelSmall", "Малое колесо: "},

                {"SceneInfoLayer.BraceLineX2", "Скобка тонкая (2x1): "},
                {"SceneInfoLayer.BraceLineX3", "Скобка тонкая (3x1): "},
                {"SceneInfoLayer.BraceSquareX2", "Скобка квадратная (2x1): "},
                {"SceneInfoLayer.BraceSquareX3", "Скобка квадратная (3x1): "},
                {"SceneInfoLayer.Lego1x1", "Лего 1x1: "},
                {"SceneInfoLayer.Lego2x1", "Лего 2x1: "},
                {"SceneInfoLayer.Roll", "Валик: "},
                {"SceneInfoLayer.RailX2", "Рельса: "},

                {"FileSelectionDialogLayer.SelectFile", "Выберите файл..."},
                {"FileSelectionDialogLayer.EnterName", "Введите имя..."},
                {"FileSelectionDialogLayer.Up", "Наверх"},
                {"FileSelectionDialogLayer.Downloads", "Загрузки"},
                {"FileSelectionDialogLayer.Save", "Сохран."},
                {"FileSelectionDialogLayer.Cancel", "Отмена"},

                {"TutorialLayer.Next", "Далее"},
                {"TutorialLayer.Welcome", "Добро пожаловать в\nFanclastic 3D Designer!\n\nВ этой программе вы можете строить модели из конструктора Fanclastic, просматривать инструкции по сборке и создавать свои собственные!"},
                {"TutorialLayer.DetailsHint", "Чтобы добавить на сцену новую деталь, перетащите соответствующую иконку с панели деталей на сцену."},
                {"TutorialLayer.SetFocusHint", "Чтобы изменить точку привязки камеры, нажмите на кнопку установки фокуса, а затем на любую деталь или точку на сцене."},
                {"TutorialLayer.ChangeColorHint", "Используйте кнопку выбора цвета, чтобы задать цвет выделенным деталям."},
                {"TutorialLayer.RotateHint", "Для поворота выделенных деталей в пространстве используйте кнопки поворота. Каждая кнопка поворачивает детали вокруг нарисованной оси соответствующего цвета."},
                {"TutorialLayer.DeleteHint", "Используйте эту кнопку, чтобы удалить выделенные детали со сцены."},
                {"TutorialLayer.ZoomHint.Base", "Используйте {0}, чтобы приблизить или удалить камеру."},
                {"TutorialLayer.ZoomHint.Wheel", "колесо мыши"},
                {"TutorialLayer.ZoomHint.Pinch", "жест двумя пальцами"},
                {"TutorialLayer.LinkedSelection", "Нажмите на деталь и удерживайте, чтобы выделить одновременно все связанные с ней детали."},

                {"ModelsSetsLayer.SetsNames.ModelsSets", "Наборы моделей"},

                {"ModelsSetsLayer.SetsNames.KBigFigures", "Большие модели"},
                {"ModelsSetsLayer.SetsNames.Cosmoclastics", "Космокластика"},
                {"ModelsSetsLayer.SetsNames.Architectics", "Архитектика"},
                {"ModelsSetsLayer.SetsNames.Geometrics", "Геометрика"},
                {"ModelsSetsLayer.SetsNames.Blasterology", "Бластерология"},
                {"ModelsSetsLayer.SetsNames.Militarics", "Милитэрика"},
                {"ModelsSetsLayer.SetsNames.Zoosaurics", "Зоозаврика"},
                {"ModelsSetsLayer.SetsNames.Monsterology", "Монстроведение"},
                {"ModelsSetsLayer.SetsNames.Robotology", "Роботоводство"},
                {"ModelsSetsLayer.SetsNames.Geometry", "Геометрия"},
                {"ModelsSetsLayer.SetsNames.Architecture", "Архитектура"},
                {"ModelsSetsLayer.SetsNames.Spaceships", "Звездолеты"},
                {"ModelsSetsLayer.SetsNames.Playground", "Детская площадка"},
                {"ModelsSetsLayer.SetsNames.Dinosaurs", "Динозавры"},
                {"ModelsSetsLayer.SetsNames.Marine", "Морской"},
                {"ModelsSetsLayer.SetsNames.Aircraft", "Воздушные суда"},
                {"ModelsSetsLayer.SetsNames.Space", "Космос"},
                {"ModelsSetsLayer.SetsNames.Mix", "Микс"},
                {"ModelsSetsLayer.SetsNames.Animals", "Животные"},
                {"ModelsSetsLayer.SetsNames.Flowers", "Цветы"},
                {"ModelsSetsLayer.SetsNames.DeerGiraff", "Олень-Жираф"},
                {"ModelsSetsLayer.SetsNames.BirdLama", "Птичка-Лама"},
                {"ModelsSetsLayer.SetsNames.PlaneShip", "Самолет-Кораблик"},
                {"ModelsSetsLayer.SetsNames.Butterflies", "Бабочки"},
                {"ModelsSetsLayer.SetsNames.Masks", "Маски"},
                {"ModelsSetsLayer.SetsNames.Racing", "Гонки"},
                {"ModelsSetsLayer.SetsNames.RallyRade", "Ралли"},
                {"ModelsSetsLayer.SetsNames.Kids200", "Kids 200"},
                {"ModelsSetsLayer.SetsNames.Kids100", "Kids 100"},
                {"ModelsSetsLayer.SetsNames.Kids40", "Kids 40"},

                {"ModelsSetsLayer.ModelsNames.GiraffeGulliver", "Жираф Гулливер"},
                {"ModelsSetsLayer.ModelsNames.DeltaSpaceship", "Дельта"},
                {"ModelsSetsLayer.ModelsNames.InfinitySpaceship", "Инфинити"},
                {"ModelsSetsLayer.ModelsNames.OmegaSpaceship", "Омега"},
                {"ModelsSetsLayer.ModelsNames.KingsCastle", "Королевский замок"},
                {"ModelsSetsLayer.ModelsNames.SkySpearTower", "Башня Небесное копьё"},
                {"ModelsSetsLayer.ModelsNames.SpaceLight", "Космический маяк"},
                {"ModelsSetsLayer.ModelsNames.Cube", "Куб"},
                {"ModelsSetsLayer.ModelsNames.FlexibleStick", "Изгибалочка"},
                {"ModelsSetsLayer.ModelsNames.Fractal", "Фрактал"},
                {"ModelsSetsLayer.ModelsNames.Globe", "Глобус"},
                {"ModelsSetsLayer.ModelsNames.Lattice", "Решетка"},
                {"ModelsSetsLayer.ModelsNames.Pyramid", "Пирамида"},
                {"ModelsSetsLayer.ModelsNames.Sphere", "Сфера"},
                {"ModelsSetsLayer.ModelsNames.Hyperblaster", "Гипербластер"},
                {"ModelsSetsLayer.ModelsNames.Megablaster", "Мегабластер"},
                {"ModelsSetsLayer.ModelsNames.Miniblaster", "Минибластер"},
                {"ModelsSetsLayer.ModelsNames.Parablaster", "Парабластер"},
                {"ModelsSetsLayer.ModelsNames.Fighter", "Истребитель"},
                {"ModelsSetsLayer.ModelsNames.Helicopter", "Вертолет"},
                {"ModelsSetsLayer.ModelsNames.Submarine", "Батискаф"},
                {"ModelsSetsLayer.ModelsNames.Tank", "Танк"},
                {"ModelsSetsLayer.ModelsNames.Dachshund", "Такса"},
                {"ModelsSetsLayer.ModelsNames.Fawn", "Олененок"},
                {"ModelsSetsLayer.ModelsNames.GiraffeKid", "Жирафик"},
                {"ModelsSetsLayer.ModelsNames.SaurKing", "Король Завр"},
                {"ModelsSetsLayer.ModelsNames.Tortilla", "Черепаха"},
                {"ModelsSetsLayer.ModelsNames.Triceratops", "Трицератопс"},
                {"ModelsSetsLayer.ModelsNames.Bossmonster", "Боссмонстрик"},
                {"ModelsSetsLayer.ModelsNames.Cyclops", "Циклоп"},
                {"ModelsSetsLayer.ModelsNames.Monster", "Монстрозаврик"},
                {"ModelsSetsLayer.ModelsNames.Radiomonster", "Радиомонстрик"},
                {"ModelsSetsLayer.ModelsNames.Smartmonster", "Смартмонстрик"},
                {"ModelsSetsLayer.ModelsNames.Stereomonster", "Стереомонстрик"},
                {"ModelsSetsLayer.ModelsNames.Telemonster", "Телемонстрик"},
                {"ModelsSetsLayer.ModelsNames.Threeclopes", "Триклоп"},
                {"ModelsSetsLayer.ModelsNames.RobotAndroid", "Андроид Андрюша"},
                {"ModelsSetsLayer.ModelsNames.RobotTransformer", "Трансформер"},
                {"ModelsSetsLayer.ModelsNames.RobotFerreous", "Железяка"},
                {"ModelsSetsLayer.ModelsNames.RobotQuadric", "Квадрик"},
                {"ModelsSetsLayer.ModelsNames.RollerRobot", "Роллер"},
                {"ModelsSetsLayer.ModelsNames.Crystal", "Кристалл"},
                {"ModelsSetsLayer.ModelsNames.Hexanom", "Гексаном"},
                {"ModelsSetsLayer.ModelsNames.Neutron", "Нейтрон"},
                {"ModelsSetsLayer.ModelsNames.Prism", "Призма"},
                {"ModelsSetsLayer.ModelsNames.Spring", "Пружинка"},
                {"ModelsSetsLayer.ModelsNames.VectorTower", "Башня Вектор"},
                {"ModelsSetsLayer.ModelsNames.ArrowTower", "Башня Стрела"},
                {"ModelsSetsLayer.ModelsNames.FortRoyal", "Крепость"},
                {"ModelsSetsLayer.ModelsNames.Skyscraper", "Небоскрёб"},
                {"ModelsSetsLayer.ModelsNames.Destroyer", "Разрушитель"},
                {"ModelsSetsLayer.ModelsNames.GlitchSender", "Шумотрон"},
                {"ModelsSetsLayer.ModelsNames.SpaceIntruder", "Космическая ищейка"},
                {"ModelsSetsLayer.ModelsNames.SpacePike", "Пик Космос"},
                {"ModelsSetsLayer.ModelsNames.TSpace", "Т-Космос"},
                {"ModelsSetsLayer.ModelsNames.CarouselTower", "Башня Каруселька "},
                {"ModelsSetsLayer.ModelsNames.JumpingBalance", "Балансир Лягушка"},
                {"ModelsSetsLayer.ModelsNames.MerryGoRound", "Карусель"},
                {"ModelsSetsLayer.ModelsNames.Seesaw", "Качалка"},
                {"ModelsSetsLayer.ModelsNames.Slide", "Горка"},
                {"ModelsSetsLayer.ModelsNames.Swing", "Качели"},
                {"ModelsSetsLayer.ModelsNames.Frusaur", "Фрузавр"},
                {"ModelsSetsLayer.ModelsNames.Catamaran", "Катамаран"},
                {"ModelsSetsLayer.ModelsNames.FairWindShip", "Бригантина"},
                {"ModelsSetsLayer.ModelsNames.SeaLightTower", "Сигнальная башня"},
                {"ModelsSetsLayer.ModelsNames.Airplane", "Самолет"},
                {"ModelsSetsLayer.ModelsNames.ControlTower", "Диспетчерская вышка"},
                {"ModelsSetsLayer.ModelsNames.FieryRocket", "Огненная ракета"},
                {"ModelsSetsLayer.ModelsNames.GammaRayDestroyer", "Истребитель Гамма"},
                {"ModelsSetsLayer.ModelsNames.SpaceRadar", "Космический радар"},
                {"ModelsSetsLayer.ModelsNames.StrikeFighterVolcano", "Штурмовик Вулкан"},
                {"ModelsSetsLayer.ModelsNames.Babycopter", "Вертолёт"},
                {"ModelsSetsLayer.ModelsNames.DragonflyPlane", "Стреколёт"},
                {"ModelsSetsLayer.ModelsNames.Giraffe", "Жираф"},
                {"ModelsSetsLayer.ModelsNames.HandBridge", "Переностик"},
                {"ModelsSetsLayer.ModelsNames.Plane", "Самолёт"},
                {"ModelsSetsLayer.ModelsNames.Robot", "Робот"},
                {"ModelsSetsLayer.ModelsNames.Tower", "Башня"},
                {"ModelsSetsLayer.ModelsNames.Umberflower", "Зонтоцветик"},
                {"ModelsSetsLayer.ModelsNames.BabyPanda", "Панда"},
                {"ModelsSetsLayer.ModelsNames.Doggie", "Пёсик"},
                {"ModelsSetsLayer.ModelsNames.Lamb", "Овечка"},
                {"ModelsSetsLayer.ModelsNames.Dandelion", "Одуванчик"},
                {"ModelsSetsLayer.ModelsNames.Lily", "Лилия"},
                {"ModelsSetsLayer.ModelsNames.BabyDeer", "Олень"},
                {"ModelsSetsLayer.ModelsNames.BabyGiraffe", "Жираф"},
                {"ModelsSetsLayer.ModelsNames.Birdy", "Птичка"},
                {"ModelsSetsLayer.ModelsNames.Lama", "Лама"},
                {"ModelsSetsLayer.ModelsNames.LittleShip", "Кораблик"},
                {"ModelsSetsLayer.ModelsNames.Hawkmoth", "Бражник"},
                {"ModelsSetsLayer.ModelsNames.Swallowtail", "Махаон"},
                {"ModelsSetsLayer.ModelsNames.Moustashed", "Усач"},
                {"ModelsSetsLayer.ModelsNames.QuadBike", "Квадроцикл"},
                {"ModelsSetsLayer.ModelsNames.RaceCar", "Болид"},
                {"ModelsSetsLayer.ModelsNames.Buggy", "Багги"},
                {"ModelsSetsLayer.ModelsNames.Motocycle", "Мотоцикл"},
                {"ModelsSetsLayer.ModelsNames.Tricycle", "Трицикл"},
                {"ModelsSetsLayer.ModelsNames.KidsAirplane", "Самолётик"},
                {"ModelsSetsLayer.ModelsNames.KidsChair", "Стул"},
                {"ModelsSetsLayer.ModelsNames.KidsDragonfly", "Стрекоза"},
                {"ModelsSetsLayer.ModelsNames.KidsLodge", "Домик"},
                {"ModelsSetsLayer.ModelsNames.KidsMan", "Человечек"},
                {"ModelsSetsLayer.ModelsNames.KidsPuppy", "Щенок"},
                {"ModelsSetsLayer.ModelsNames.KidsSpider", "Паук"},
                {"ModelsSetsLayer.ModelsNames.KidsTree", "Дерево"},
                {"ModelsSetsLayer.ModelsNames.KidsTruck", "Грузовичок"},
                {"ModelsSetsLayer.ModelsNames.KidsTruckCrane", "Автокран"},
                {"ModelsSetsLayer.ModelsNames.KidsVase", "Вазочка"},
                {"ModelsSetsLayer.ModelsNames.KidsBench", "Скамейка"},
                {"ModelsSetsLayer.ModelsNames.KidsTable", "Столик"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(1)", "Решётка 3x3 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(2)", "Решётка 3x3 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(1)", "Решётка 6x2 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(2)", "Решётка 6x2 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(3)", "Решётка 6x2 (3)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(4)", "Решётка 6x2 (4)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(5)", "Решётка 6x2 (5)"},
                {"ModelsSetsLayer.ModelsNames.Tetrahedron", "Тетраэдр"},
                {"ModelsSetsLayer.ModelsNames.Unbreakable", "Нерушимая"},
                {"ModelsSetsLayer.ModelsNames.Logo", "Лого"},
            },
            new Dictionary<string, string>
            {
                {"EditorLayer.ActiveColor", "Aktive Farbe"},
                {"EditorLayer.Details", "Details"},

                {"Menu.Menu", "Menü"},
                {"Menu.NewScene", "Neue Szene"},
                {"Menu.Save", "Speichern..."},
                {"Menu.Load", "Herunterladen..."},
                {"Menu.Export", "Export..."},
                {"Menu.SceneInfo", "Szenen info"},
                {"Menu.ModelsSets", "Modelle"},
                {"Menu.Help", "Hilfe"},
                {"Menu.Exit", "Beenden"},

                {"ModeSwitcher.Editor", "Editor"},
                {"ModeSwitcher.Instructions", "Anleitungen"},

                {"SceneInfoLayer.Copy", "Kopieren"},
                {"SceneInfoLayer.Height", "Höhe:"},
                {"SceneInfoLayer.Length", "Länge:"},
                {"SceneInfoLayer.Width", "Breite:"},
                {"SceneInfoLayer.Weight", "Gewicht:"},
                {"SceneInfoLayer.TotalDetails", "Gesamtzahl der Details"},
                {"SceneInfoLayer.cm", "cm"},
                {"SceneInfoLayer.gram", "g"},

                {"SceneInfoLayer.Black", "Schwarz"},
                {"SceneInfoLayer.Blue", "Blau"},
                {"SceneInfoLayer.Brown", "Braun"},
                {"SceneInfoLayer.Gray", "Grau"},
                {"SceneInfoLayer.Green", "Grün"},
                {"SceneInfoLayer.Red", "Rot"},
                {"SceneInfoLayer.White", "Weiß"},
                {"SceneInfoLayer.Yellow", "Gelb"},

                {"SceneInfoLayer.BraceLineX2", "Dünne Klammer (2x1): "},
                {"SceneInfoLayer.BraceLineX3", "Dünne Klammer (3x1): "},
                {"SceneInfoLayer.BraceSquareX2", "Quadratische Klammer (2x1): "},
                {"SceneInfoLayer.BraceSquareX3", "Quadratische Klammer (3x1): "},
                {"SceneInfoLayer.Lego1x1", "Lego 1x1: "},
                {"SceneInfoLayer.Lego2x1", "Lego 2x1: "},
                {"SceneInfoLayer.Roll", "Rolle: "},
                {"SceneInfoLayer.RailX2", "Schiene: "},

                {"SceneInfoLayer.Axle1.0", "Achse 1.0: "},
                {"SceneInfoLayer.Axle2.0", "Achse 2.0: "},
                {"SceneInfoLayer.Axle2.5", "Achse 2.5: "},
                {"SceneInfoLayer.Axle3.0", "Achse 3.0: "},
                {"SceneInfoLayer.Axle3.5", "Achse 3.5: "},
                {"SceneInfoLayer.Axle8.0", "Achse 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Kegelradgetriebe: "},
                {"SceneInfoLayer.AxleCoupling", "Kupplung: "},
                {"SceneInfoLayer.AxleHub3x1", "Nabe (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Nabe (5x1): "},
                {"SceneInfoLayer.AxleTip", "Spitze: "},
                {"SceneInfoLayer.AxleWasher", "Scheibe: "},
                {"SceneInfoLayer.AxleWasherToothed", "Zahnscheibe: "},
                {"SceneInfoLayer.AxleWheelBig", "Großes Rad: "},
                {"SceneInfoLayer.AxleWheelSmall", "Kleines Rad: "},

                {"FileSelectionDialogLayer.SelectFile", "Datei auswählen..."},
                {"FileSelectionDialogLayer.EnterName", "Namen eingeben..."},
                {"FileSelectionDialogLayer.Up", "Nach oben "},
                {"FileSelectionDialogLayer.Downloads", "Herunterladen"},
                {"FileSelectionDialogLayer.Save", "Speichern"},
                {"FileSelectionDialogLayer.Cancel", "Abbrechen"},

                {"TutorialLayer.Next", "Nächster"},
                {"TutorialLayer.Welcome", "Willkommen bei\nFanclastic 3D Designer!\n\nIn diesem Programm können Sie Modelle aus dem Fanclastic-Baukasten erstellen, Bauanleitungen ansehen und eigene erstellen!"},
                {"TutorialLayer.DetailsHint", "Um der Szene ein neues Detail hinzuzufügen, ziehen Sie das entsprechende Symbol aus der Detail-Palette in die Szene"},
                {"TutorialLayer.SetFocusHint", "Um den Fangpunkt der Kamera zu ändern, klicken Sie auf die Schaltfläche für die Fokuseinstellung und dann auf jeden Punkt oder jedes Detail auf der Bühne.."},
                {"TutorialLayer.ChangeColorHint", "Verwenden Sie die Farbauswahltaste, um die Farbe für die markierten Elemente festzulegen."},
                {"TutorialLayer.RotateHint", "Verwenden Sie die Drehschaltflächen, um die ausgewählten Details im Raum zu drehen. Jede Schaltfläche dreht die Details um die gezeichnete Achse der entsprechenden Farbe."},
                {"TutorialLayer.DeleteHint", "Verwenden Sie diese Schaltfläche, um ausgewählte Details aus der Szene zu löschen.."},
                {"TutorialLayer.ZoomHint.Base", "Verwenden Sie {0}, um die Kamera zu vergrößern oder zu verkleinern."},
                {"TutorialLayer.ZoomHint.Wheel", "Mausrad"},
                {"TutorialLayer.ZoomHint.Pinch", "Zwei-Finger-Geste"},
                {"TutorialLayer.LinkedSelection", "Klicken Sie auf das Detail und halten Sie es gedrückt, um alle zugehörigen Details gleichzeitig auszuwählen."},

                {"ModelsSetsLayer.SetsNames.ModelsSets", "Models sets"},

                {"ModelsSetsLayer.SetsNames.KBigFigures", "Big Figures"},
                {"ModelsSetsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
                {"ModelsSetsLayer.SetsNames.Architectics", "Architectics"},
                {"ModelsSetsLayer.SetsNames.Geometrics", "Geometrics"},
                {"ModelsSetsLayer.SetsNames.Blasterology", "Blasterology"},
                {"ModelsSetsLayer.SetsNames.Militarics", "Militarics"},
                {"ModelsSetsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
                {"ModelsSetsLayer.SetsNames.Monsterology", "Monsterology"},
                {"ModelsSetsLayer.SetsNames.Robotology", "Robotology"},
                {"ModelsSetsLayer.SetsNames.Geometry", "Geometry"},
                {"ModelsSetsLayer.SetsNames.Architecture", "Architecture"},
                {"ModelsSetsLayer.SetsNames.Spaceships", "Spaceships"},
                {"ModelsSetsLayer.SetsNames.Playground", "Playground"},
                {"ModelsSetsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
                {"ModelsSetsLayer.SetsNames.Marine", "Marine"},
                {"ModelsSetsLayer.SetsNames.Aircraft", "Aircraft"},
                {"ModelsSetsLayer.SetsNames.Space", "Space"},
                {"ModelsSetsLayer.SetsNames.Mix", "Mix"},
                {"ModelsSetsLayer.SetsNames.Animals", "Animals"},
                {"ModelsSetsLayer.SetsNames.Flowers", "Flowers"},
                {"ModelsSetsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
                {"ModelsSetsLayer.SetsNames.BirdLama", "Bird-Lama"},
                {"ModelsSetsLayer.SetsNames.PlaneShip", "Plane-Ship"},
                {"ModelsSetsLayer.SetsNames.Butterflies", "Butterflies"},
                {"ModelsSetsLayer.SetsNames.Masks", "Masks"},
                {"ModelsSetsLayer.SetsNames.Racing", "Racing"},
                {"ModelsSetsLayer.SetsNames.RallyRade", "Rally Rade"},
                {"ModelsSetsLayer.SetsNames.Kids200", "Kids 200"},
                {"ModelsSetsLayer.SetsNames.Kids100", "Kids 100"},
                {"ModelsSetsLayer.SetsNames.Kids40", "Kids 40"},

                {"ModelsSetsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
                {"ModelsSetsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
                {"ModelsSetsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
                {"ModelsSetsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
                {"ModelsSetsLayer.ModelsNames.KingsCastle", "King's Castle"},
                {"ModelsSetsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
                {"ModelsSetsLayer.ModelsNames.SpaceLight", "Space Light"},
                {"ModelsSetsLayer.ModelsNames.Cube", "Cube"},
                {"ModelsSetsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
                {"ModelsSetsLayer.ModelsNames.Fractal", "Fractal"},
                {"ModelsSetsLayer.ModelsNames.Globe", "Globe"},
                {"ModelsSetsLayer.ModelsNames.Lattice", "Lattice"},
                {"ModelsSetsLayer.ModelsNames.Pyramid", "Pyramid"},
                {"ModelsSetsLayer.ModelsNames.Sphere", "Sphere"},
                {"ModelsSetsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
                {"ModelsSetsLayer.ModelsNames.Megablaster", "Megablaster"},
                {"ModelsSetsLayer.ModelsNames.Miniblaster", "Miniblaster"},
                {"ModelsSetsLayer.ModelsNames.Parablaster", "Parablaster"},
                {"ModelsSetsLayer.ModelsNames.Fighter", "Fighter"},
                {"ModelsSetsLayer.ModelsNames.Helicopter", "Helicopter"},
                {"ModelsSetsLayer.ModelsNames.Submarine", "Submarine"},
                {"ModelsSetsLayer.ModelsNames.Tank", "Tank"},
                {"ModelsSetsLayer.ModelsNames.Dachshund", "Dachshund"},
                {"ModelsSetsLayer.ModelsNames.Fawn", "Fawn"},
                {"ModelsSetsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
                {"ModelsSetsLayer.ModelsNames.SaurKing", "Saur King"},
                {"ModelsSetsLayer.ModelsNames.Tortilla", "Tortilla"},
                {"ModelsSetsLayer.ModelsNames.Triceratops", "Triceratops"},
                {"ModelsSetsLayer.ModelsNames.Bossmonster", "Bossmonster"},
                {"ModelsSetsLayer.ModelsNames.Cyclops", "Cyclops"},
                {"ModelsSetsLayer.ModelsNames.Monster", "Monster"},
                {"ModelsSetsLayer.ModelsNames.Radiomonster", "Radiomonster"},
                {"ModelsSetsLayer.ModelsNames.Smartmonster", "Smartmonster"},
                {"ModelsSetsLayer.ModelsNames.Stereomonster", "Stereomonster"},
                {"ModelsSetsLayer.ModelsNames.Telemonster", "Telemonster"},
                {"ModelsSetsLayer.ModelsNames.Threeclopes", "Threeclopes"},
                {"ModelsSetsLayer.ModelsNames.RobotAndroid", "Robot 1"},
                {"ModelsSetsLayer.ModelsNames.RobotTransformer", "Robot 4"},
                {"ModelsSetsLayer.ModelsNames.RobotFerreous", "Robot 2"},
                {"ModelsSetsLayer.ModelsNames.RobotQuadric", "Robot 3"},
                {"ModelsSetsLayer.ModelsNames.RollerRobot", "Roller Robot"},
                {"ModelsSetsLayer.ModelsNames.Crystal", "Crystal"},
                {"ModelsSetsLayer.ModelsNames.Hexanom", "Hexanom"},
                {"ModelsSetsLayer.ModelsNames.Neutron", "Neutron"},
                {"ModelsSetsLayer.ModelsNames.Prism", "Prism"},
                {"ModelsSetsLayer.ModelsNames.Spring", "Spring"},
                {"ModelsSetsLayer.ModelsNames.VectorTower", "Vector Tower"},
                {"ModelsSetsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
                {"ModelsSetsLayer.ModelsNames.FortRoyal", "Fort Royal"},
                {"ModelsSetsLayer.ModelsNames.Skyscraper", "Skyscraper"},
                {"ModelsSetsLayer.ModelsNames.Destroyer", "Destroyer"},
                {"ModelsSetsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
                {"ModelsSetsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
                {"ModelsSetsLayer.ModelsNames.SpacePike", "Space Pike"},
                {"ModelsSetsLayer.ModelsNames.TSpace", "TSpace"},
                {"ModelsSetsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
                {"ModelsSetsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
                {"ModelsSetsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
                {"ModelsSetsLayer.ModelsNames.Seesaw", "Seesaw"},
                {"ModelsSetsLayer.ModelsNames.Slide", "Slide"},
                {"ModelsSetsLayer.ModelsNames.Swing", "Swing"},
                {"ModelsSetsLayer.ModelsNames.Frusaur", "Frusaur"},
                {"ModelsSetsLayer.ModelsNames.Catamaran", "Catamaran"},
                {"ModelsSetsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
                {"ModelsSetsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
                {"ModelsSetsLayer.ModelsNames.Airplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.ControlTower", "Control Tower"},
                {"ModelsSetsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
                {"ModelsSetsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
                {"ModelsSetsLayer.ModelsNames.SpaceRadar", "Space Radar"},
                {"ModelsSetsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
                {"ModelsSetsLayer.ModelsNames.Babycopter", "Babycopter"},
                {"ModelsSetsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
                {"ModelsSetsLayer.ModelsNames.Giraffe", "Giraffe"},
                {"ModelsSetsLayer.ModelsNames.HandBridge", "Hand-bridge"},
                {"ModelsSetsLayer.ModelsNames.Plane", "Plane"},
                {"ModelsSetsLayer.ModelsNames.Robot", "Robot"},
                {"ModelsSetsLayer.ModelsNames.Tower", "Tower"},
                {"ModelsSetsLayer.ModelsNames.Umberflower", "Umberflower"},
                {"ModelsSetsLayer.ModelsNames.BabyPanda", "Baby Panda"},
                {"ModelsSetsLayer.ModelsNames.Doggie", "Doggie"},
                {"ModelsSetsLayer.ModelsNames.Lamb", "Lamb"},
                {"ModelsSetsLayer.ModelsNames.Dandelion", "Dandelion"},
                {"ModelsSetsLayer.ModelsNames.Lily", "Lily"},
                {"ModelsSetsLayer.ModelsNames.BabyDeer", "Baby Deer"},
                {"ModelsSetsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
                {"ModelsSetsLayer.ModelsNames.Birdy", "Birdy"},
                {"ModelsSetsLayer.ModelsNames.Lama", "Lama"},
                {"ModelsSetsLayer.ModelsNames.LittleShip", "Little Ship"},
                {"ModelsSetsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
                {"ModelsSetsLayer.ModelsNames.Swallowtail", "Swallowtail"},
                {"ModelsSetsLayer.ModelsNames.Moustashed", "Moustashed"},
                {"ModelsSetsLayer.ModelsNames.QuadBike", "Quad Bike"},
                {"ModelsSetsLayer.ModelsNames.RaceCar", "Race Car"},
                {"ModelsSetsLayer.ModelsNames.Buggy", "Buggy"},
                {"ModelsSetsLayer.ModelsNames.Motocycle", "Motocycle"},
                {"ModelsSetsLayer.ModelsNames.Tricycle", "Tricycle"},
                {"ModelsSetsLayer.ModelsNames.KidsAirplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.KidsChair", "Chair"},
                {"ModelsSetsLayer.ModelsNames.KidsDragonfly", "Dragonfly"},
                {"ModelsSetsLayer.ModelsNames.KidsLodge", "Lodge"},
                {"ModelsSetsLayer.ModelsNames.KidsMan", "Little Man"},
                {"ModelsSetsLayer.ModelsNames.KidsPuppy", "Puppy"},
                {"ModelsSetsLayer.ModelsNames.KidsSpider", "Spider"},
                {"ModelsSetsLayer.ModelsNames.KidsTree", "Tree"},
                {"ModelsSetsLayer.ModelsNames.KidsTruck", "Truck"},
                {"ModelsSetsLayer.ModelsNames.KidsTruckCrane", "Truck Crane"},
                {"ModelsSetsLayer.ModelsNames.KidsVase", "Vase"},
                {"ModelsSetsLayer.ModelsNames.KidsBench", "Bench"},
                {"ModelsSetsLayer.ModelsNames.KidsTable", "Table"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 (3)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 (4)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 (5)"},
                {"ModelsSetsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
                {"ModelsSetsLayer.ModelsNames.Unbreakable", "Unbreakable"},
                {"ModelsSetsLayer.ModelsNames.Logo", "Logo"},
            },
            new Dictionary<string, string>
            {
                {"EditorLayer.ActiveColor", "Kolory"},
                {"EditorLayer.Details", "Elementy"},

                {"Menu.Menu", "Menu"},
                {"Menu.NewScene", "Nowy projekt"},
                {"Menu.Save", "Zapisz..."},
                {"Menu.Load", "Wczytaj..."},
                {"Menu.Export", "Eksportuj..."},
                {"Menu.SceneInfo", "Szczegóły projektu"},
                {"Menu.ModelsSets", "Modele"},
                {"Menu.Help", "Pomoc"},
                {"Menu.Exit", "Wyjście"},

                {"ModeSwitcher.Editor", "Tryb edycji"},
                {"ModeSwitcher.Instructions", "Tryb instrukcji"},

                {"SceneInfoLayer.Copy", "Kopiuj"},
                {"SceneInfoLayer.Height", "Wysokość:"},
                {"SceneInfoLayer.Length", "Długość:"},
                {"SceneInfoLayer.Width", "Szerokość:"},
                {"SceneInfoLayer.Weight", "Waga:"},
                {"SceneInfoLayer.TotalDetails", "Wszystkich elementów:"},
                {"SceneInfoLayer.cm", "cm"},
                {"SceneInfoLayer.gram", "g"},

                {"SceneInfoLayer.Black", "Czarny"},
                {"SceneInfoLayer.Blue", "Niebieski"},
                {"SceneInfoLayer.Brown", "Brązowy"},
                {"SceneInfoLayer.Gray", "Szary"},
                {"SceneInfoLayer.Green", "Zielony"},
                {"SceneInfoLayer.Red", "Czerwony"},
                {"SceneInfoLayer.White", "Biały"},
                {"SceneInfoLayer.Yellow", "Żółty"},

                {"SceneInfoLayer.BraceLineX2", "Łacznik wewnętrzny (2x1): "},
                {"SceneInfoLayer.BraceLineX3", "Łącznik wewnętrzny (3x1): "},
                {"SceneInfoLayer.BraceSquareX2", "Łącznik zewnętrzny (2x1): "},
                {"SceneInfoLayer.BraceSquareX3", "Łącznik zewnętrzny (3x1): "},
                {"SceneInfoLayer.Lego1x1", "Lego adapter 1x1: "},
                {"SceneInfoLayer.Lego2x1", "Lego adapter 2x1: "},
                {"SceneInfoLayer.Roll", "Zawias: "},
                {"SceneInfoLayer.RailX2", "Szyna: "},

                {"SceneInfoLayer.Axle1.0", "Oś 1.0: "},
                {"SceneInfoLayer.Axle2.0", "Oś 2.0: "},
                {"SceneInfoLayer.Axle2.5", "Oś 2.5: "},
                {"SceneInfoLayer.Axle3.0", "Oś 3.0: "},
                {"SceneInfoLayer.Axle3.5", "Oś 3.5: "},
                {"SceneInfoLayer.Axle8.0", "Oś 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Przekładnia stożkowa: "},
                {"SceneInfoLayer.AxleCoupling", "Sprzęganie: "},
                {"SceneInfoLayer.AxleHub3x1", "Piasta (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Piasta (5x1): "},
                {"SceneInfoLayer.AxleTip", "Wskazówka: "},
                {"SceneInfoLayer.AxleWasher", "Podkładka: "},
                {"SceneInfoLayer.AxleWasherToothed", "Podkładka zębata: "},
                {"SceneInfoLayer.AxleWheelBig", "Wielkie koło: "},
                {"SceneInfoLayer.AxleWheelSmall", "Małe koło: "},

                {"FileSelectionDialogLayer.SelectFile", "Wybierz projekt..."},
                {"FileSelectionDialogLayer.EnterName", "Nazwij projekt..."},
                {"FileSelectionDialogLayer.Up", "Do góry"},
                {"FileSelectionDialogLayer.Downloads", "Pobrane"},
                {"FileSelectionDialogLayer.Save", "Zapisz"},
                {"FileSelectionDialogLayer.Cancel", "Anuluj"},

                {"TutorialLayer.Next", "Dalej"},
                {"TutorialLayer.Welcome", "Witaj w\nFanclastic 3D Designer™!\n\nTen program umożliwi Ci projektowanie własnych budowli Fanclastic i generowanie do nich animowanych instrukcji oraz przeglądanie już istniejących projektów. \n\nwww.fanclastic.pl"},
                {"TutorialLayer.DetailsHint", "Aby dodać element do obecnego projektu, przeciągnij odpowiednią ikonę z panelu elementów na wybrane miejsce na planie."},
                {"TutorialLayer.SetFocusHint", "Aby zmienić punkt widzenia kamery, kliknij przycisk ustawienia ostrości, a następnie na dowolny element lub punkt na planie."},
                {"TutorialLayer.ChangeColorHint", "Użyj przycisku wyboru koloru, aby zmienić barwę dla użytych elementów."},
                {"TutorialLayer.RotateHint", "Aby obrócić wybrany element, użyj przycisków obrotu, każdy z nich obraca elementy wokół danej osi odpowiedniego koloru."},
                {"TutorialLayer.DeleteHint", "Użyj tego przycisku, aby usunąć wybrane elementy z planu."},
                {"TutorialLayer.ZoomHint.Base", "Użyj  {0} aby powiększyć i pomniejszyć zbliżenie kamery."},
                {"TutorialLayer.ZoomHint.Wheel", "kółka w myszce"},
                {"TutorialLayer.ZoomHint.Pinch", "uszczypnięcia"},
                {"TutorialLayer.LinkedSelection", "Kliknij i przytrzymaj element, aby zobaczyć wszystkie połączone części i obrócić budowlę przyciskami obrotu."},

                {"ModelsSetsLayer.SetsNames.ModelsSets", "Models sets"},

                {"ModelsSetsLayer.SetsNames.KBigFigures", "Big Figures"},
                {"ModelsSetsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
                {"ModelsSetsLayer.SetsNames.Architectics", "Architectics"},
                {"ModelsSetsLayer.SetsNames.Geometrics", "Geometrics"},
                {"ModelsSetsLayer.SetsNames.Blasterology", "Blasterology"},
                {"ModelsSetsLayer.SetsNames.Militarics", "Militarics"},
                {"ModelsSetsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
                {"ModelsSetsLayer.SetsNames.Monsterology", "Monsterology"},
                {"ModelsSetsLayer.SetsNames.Robotology", "Robotology"},
                {"ModelsSetsLayer.SetsNames.Geometry", "Geometry"},
                {"ModelsSetsLayer.SetsNames.Architecture", "Architecture"},
                {"ModelsSetsLayer.SetsNames.Spaceships", "Spaceships"},
                {"ModelsSetsLayer.SetsNames.Playground", "Playground"},
                {"ModelsSetsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
                {"ModelsSetsLayer.SetsNames.Marine", "Marine"},
                {"ModelsSetsLayer.SetsNames.Aircraft", "Aircraft"},
                {"ModelsSetsLayer.SetsNames.Space", "Space"},
                {"ModelsSetsLayer.SetsNames.Mix", "Mix"},
                {"ModelsSetsLayer.SetsNames.Animals", "Animals"},
                {"ModelsSetsLayer.SetsNames.Flowers", "Flowers"},
                {"ModelsSetsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
                {"ModelsSetsLayer.SetsNames.BirdLama", "Bird-Lama"},
                {"ModelsSetsLayer.SetsNames.PlaneShip", "Plane-Ship"},
                {"ModelsSetsLayer.SetsNames.Butterflies", "Butterflies"},
                {"ModelsSetsLayer.SetsNames.Masks", "Masks"},
                {"ModelsSetsLayer.SetsNames.Racing", "Racing"},
                {"ModelsSetsLayer.SetsNames.RallyRade", "Rally Rade"},
                {"ModelsSetsLayer.SetsNames.Kids200", "Kids 200"},
                {"ModelsSetsLayer.SetsNames.Kids100", "Kids 100"},
                {"ModelsSetsLayer.SetsNames.Kids40", "Kids 40"},

                {"ModelsSetsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
                {"ModelsSetsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
                {"ModelsSetsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
                {"ModelsSetsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
                {"ModelsSetsLayer.ModelsNames.KingsCastle", "King's Castle"},
                {"ModelsSetsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
                {"ModelsSetsLayer.ModelsNames.SpaceLight", "Space Light"},
                {"ModelsSetsLayer.ModelsNames.Cube", "Cube"},
                {"ModelsSetsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
                {"ModelsSetsLayer.ModelsNames.Fractal", "Fractal"},
                {"ModelsSetsLayer.ModelsNames.Globe", "Globe"},
                {"ModelsSetsLayer.ModelsNames.Lattice", "Lattice"},
                {"ModelsSetsLayer.ModelsNames.Pyramid", "Pyramid"},
                {"ModelsSetsLayer.ModelsNames.Sphere", "Sphere"},
                {"ModelsSetsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
                {"ModelsSetsLayer.ModelsNames.Megablaster", "Megablaster"},
                {"ModelsSetsLayer.ModelsNames.Miniblaster", "Miniblaster"},
                {"ModelsSetsLayer.ModelsNames.Parablaster", "Parablaster"},
                {"ModelsSetsLayer.ModelsNames.Fighter", "Fighter"},
                {"ModelsSetsLayer.ModelsNames.Helicopter", "Helicopter"},
                {"ModelsSetsLayer.ModelsNames.Submarine", "Submarine"},
                {"ModelsSetsLayer.ModelsNames.Tank", "Tank"},
                {"ModelsSetsLayer.ModelsNames.Dachshund", "Dachshund"},
                {"ModelsSetsLayer.ModelsNames.Fawn", "Fawn"},
                {"ModelsSetsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
                {"ModelsSetsLayer.ModelsNames.SaurKing", "Saur King"},
                {"ModelsSetsLayer.ModelsNames.Tortilla", "Tortilla"},
                {"ModelsSetsLayer.ModelsNames.Triceratops", "Triceratops"},
                {"ModelsSetsLayer.ModelsNames.Bossmonster", "Bossmonster"},
                {"ModelsSetsLayer.ModelsNames.Cyclops", "Cyclops"},
                {"ModelsSetsLayer.ModelsNames.Monster", "Monster"},
                {"ModelsSetsLayer.ModelsNames.Radiomonster", "Radiomonster"},
                {"ModelsSetsLayer.ModelsNames.Smartmonster", "Smartmonster"},
                {"ModelsSetsLayer.ModelsNames.Stereomonster", "Stereomonster"},
                {"ModelsSetsLayer.ModelsNames.Telemonster", "Telemonster"},
                {"ModelsSetsLayer.ModelsNames.Threeclopes", "Threeclopes"},
                {"ModelsSetsLayer.ModelsNames.RobotAndroid", "Robot 1"},
                {"ModelsSetsLayer.ModelsNames.RobotTransformer", "Robot 4"},
                {"ModelsSetsLayer.ModelsNames.RobotFerreous", "Robot 2"},
                {"ModelsSetsLayer.ModelsNames.RobotQuadric", "Robot 3"},
                {"ModelsSetsLayer.ModelsNames.RollerRobot", "Roller Robot"},
                {"ModelsSetsLayer.ModelsNames.Crystal", "Crystal"},
                {"ModelsSetsLayer.ModelsNames.Hexanom", "Hexanom"},
                {"ModelsSetsLayer.ModelsNames.Neutron", "Neutron"},
                {"ModelsSetsLayer.ModelsNames.Prism", "Prism"},
                {"ModelsSetsLayer.ModelsNames.Spring", "Spring"},
                {"ModelsSetsLayer.ModelsNames.VectorTower", "Vector Tower"},
                {"ModelsSetsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
                {"ModelsSetsLayer.ModelsNames.FortRoyal", "Fort Royal"},
                {"ModelsSetsLayer.ModelsNames.Skyscraper", "Skyscraper"},
                {"ModelsSetsLayer.ModelsNames.Destroyer", "Destroyer"},
                {"ModelsSetsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
                {"ModelsSetsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
                {"ModelsSetsLayer.ModelsNames.SpacePike", "Space Pike"},
                {"ModelsSetsLayer.ModelsNames.TSpace", "TSpace"},
                {"ModelsSetsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
                {"ModelsSetsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
                {"ModelsSetsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
                {"ModelsSetsLayer.ModelsNames.Seesaw", "Seesaw"},
                {"ModelsSetsLayer.ModelsNames.Slide", "Slide"},
                {"ModelsSetsLayer.ModelsNames.Swing", "Swing"},
                {"ModelsSetsLayer.ModelsNames.Frusaur", "Frusaur"},
                {"ModelsSetsLayer.ModelsNames.Catamaran", "Catamaran"},
                {"ModelsSetsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
                {"ModelsSetsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
                {"ModelsSetsLayer.ModelsNames.Airplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.ControlTower", "Control Tower"},
                {"ModelsSetsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
                {"ModelsSetsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
                {"ModelsSetsLayer.ModelsNames.SpaceRadar", "Space Radar"},
                {"ModelsSetsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
                {"ModelsSetsLayer.ModelsNames.Babycopter", "Babycopter"},
                {"ModelsSetsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
                {"ModelsSetsLayer.ModelsNames.Giraffe", "Giraffe"},
                {"ModelsSetsLayer.ModelsNames.HandBridge", "Hand-bridge"},
                {"ModelsSetsLayer.ModelsNames.Plane", "Plane"},
                {"ModelsSetsLayer.ModelsNames.Robot", "Robot"},
                {"ModelsSetsLayer.ModelsNames.Tower", "Tower"},
                {"ModelsSetsLayer.ModelsNames.Umberflower", "Umberflower"},
                {"ModelsSetsLayer.ModelsNames.BabyPanda", "Baby Panda"},
                {"ModelsSetsLayer.ModelsNames.Doggie", "Doggie"},
                {"ModelsSetsLayer.ModelsNames.Lamb", "Lamb"},
                {"ModelsSetsLayer.ModelsNames.Dandelion", "Dandelion"},
                {"ModelsSetsLayer.ModelsNames.Lily", "Lily"},
                {"ModelsSetsLayer.ModelsNames.BabyDeer", "Baby Deer"},
                {"ModelsSetsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
                {"ModelsSetsLayer.ModelsNames.Birdy", "Birdy"},
                {"ModelsSetsLayer.ModelsNames.Lama", "Lama"},
                {"ModelsSetsLayer.ModelsNames.LittleShip", "Little Ship"},
                {"ModelsSetsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
                {"ModelsSetsLayer.ModelsNames.Swallowtail", "Swallowtail"},
                {"ModelsSetsLayer.ModelsNames.Moustashed", "Moustashed"},
                {"ModelsSetsLayer.ModelsNames.QuadBike", "Quad Bike"},
                {"ModelsSetsLayer.ModelsNames.RaceCar", "Race Car"},
                {"ModelsSetsLayer.ModelsNames.Buggy", "Buggy"},
                {"ModelsSetsLayer.ModelsNames.Motocycle", "Motocycle"},
                {"ModelsSetsLayer.ModelsNames.Tricycle", "Tricycle"},
                {"ModelsSetsLayer.ModelsNames.KidsAirplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.KidsChair", "Chair"},
                {"ModelsSetsLayer.ModelsNames.KidsDragonfly", "Dragonfly"},
                {"ModelsSetsLayer.ModelsNames.KidsLodge", "Lodge"},
                {"ModelsSetsLayer.ModelsNames.KidsMan", "Little Man"},
                {"ModelsSetsLayer.ModelsNames.KidsPuppy", "Puppy"},
                {"ModelsSetsLayer.ModelsNames.KidsSpider", "Spider"},
                {"ModelsSetsLayer.ModelsNames.KidsTree", "Tree"},
                {"ModelsSetsLayer.ModelsNames.KidsTruck", "Truck"},
                {"ModelsSetsLayer.ModelsNames.KidsTruckCrane", "Truck Crane"},
                {"ModelsSetsLayer.ModelsNames.KidsVase", "Vase"},
                {"ModelsSetsLayer.ModelsNames.KidsBench", "Bench"},
                {"ModelsSetsLayer.ModelsNames.KidsTable", "Table"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 (3)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 (4)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 (5)"},
                {"ModelsSetsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
                {"ModelsSetsLayer.ModelsNames.Unbreakable", "Unbreakable"},
                {"ModelsSetsLayer.ModelsNames.Logo", "Logo"},
            },
            new Dictionary<string, string>
            {
                {"EditorLayer.ActiveColor", "גוון פעיל"},
                {"EditorLayer.Details", "רכיבים"},

                {"Menu.Menu", "תפריט"},
                {"Menu.NewScene", "פעולה חדשה"},
                {"Menu.Save", "שמירה..."},
                {"Menu.Load", "פתיחת קובץ..."},
                {"Menu.Export", "ייצוא..."},
                {"Menu.SceneInfo", "מידת הזירה"},
                {"Menu.ModelsSets", "דגמים"},
                {"Menu.Help", "עזרה"},
                {"Menu.Exit", "יציאה"},

                {"ModeSwitcher.Editor", "עריכה"},
                {"ModeSwitcher.Instructions", "הוראות"},

                {"SceneInfoLayer.Copy", "העתק"},
                {"SceneInfoLayer.Height", "גובה"},
                {"SceneInfoLayer.Length", "אורך"},
                {"SceneInfoLayer.Width", "עובי"},
                {"SceneInfoLayer.Weight", "משקל"},
                {"SceneInfoLayer.TotalDetails", "סה\"כ רכיבים"},
                {"SceneInfoLayer.cm", "ס\"מ"},
                {"SceneInfoLayer.gram", "גרם"},

                {"SceneInfoLayer.Black", "שחור"},
                {"SceneInfoLayer.Blue", "כחול"},
                {"SceneInfoLayer.Brown", "חום"},
                {"SceneInfoLayer.Gray", "אפור"},
                {"SceneInfoLayer.Green", "ירוק"},
                {"SceneInfoLayer.Red", "אדום"},
                {"SceneInfoLayer.White", "לבן"},
                {"SceneInfoLayer.Yellow", "צהוב"},

                {"SceneInfoLayer.BraceLineX2","סוגר מסולסל" + " (2x1) "},
                {"SceneInfoLayer.BraceLineX3", "סוגר מסולסל" + " (3x1) "},
                {"SceneInfoLayer.BraceSquareX2", "סוגר מלבני" + " (2x1) "},
                {"SceneInfoLayer.BraceSquareX3", "סוגר מלבני" + " (3x1) "},
                {"SceneInfoLayer.Lego1x1", "לגו" + " 1x1 "},
                {"SceneInfoLayer.Lego2x1", "לגו" + " 2x1 "},
                {"SceneInfoLayer.Roll", "רול "},
                {"SceneInfoLayer.RailX2", "מסילה "},

                {"SceneInfoLayer.Axle1.0", "סרן" + " 1.0 "},
                {"SceneInfoLayer.Axle2.0", "סרן" + " 2.0 "},
                {"SceneInfoLayer.Axle2.5", "סרן" + " 2.5 "},
                {"SceneInfoLayer.Axle3.0", "סרן" + " 3.0 "},
                {"SceneInfoLayer.Axle3.5", "סרן" + " 3.5 "},
                {"SceneInfoLayer.Axle8.0", "סרן" + " 8.0 "},

                {"SceneInfoLayer.AxleBevelGear", "ציוד שפוע "},
                {"SceneInfoLayer.AxleCoupling", "מצמד "},
                {"SceneInfoLayer.AxleHub3x1", "רכזת" + " (3x1) "},
                {"SceneInfoLayer.AxleHub5x1", "רכזת" + " (5x1) "},
                {"SceneInfoLayer.AxleTip", "חוֹד "},
                {"SceneInfoLayer.AxleWasher", "דיסקוס "},
                {"SceneInfoLayer.AxleWasherToothed", "דיסקוס מחורץ "},
                {"SceneInfoLayer.AxleWheelBig", "גלגל גדול "},
                {"SceneInfoLayer.AxleWheelSmall", "גלגל קטן "},

                {"FileSelectionDialogLayer.SelectFile", "בחר קובץ..."},
                {"FileSelectionDialogLayer.EnterName", "הזן שם..."},
                {"FileSelectionDialogLayer.Up", "למעלה"},
                {"FileSelectionDialogLayer.Downloads", "הורדות"},
                {"FileSelectionDialogLayer.Save", "שמירה"},
                {"FileSelectionDialogLayer.Cancel", "ביטול"},

                {"TutorialLayer.Next", "הבא"},
                {"TutorialLayer.Welcome", "ברוכים הבאים ל\nFanclastic 3D Designer!\n\nתוכנית זו מסייעת לך לבנות מודלים ,להציג הוראות הרכבה וליצור מודלים משלך."},
                {"TutorialLayer.DetailsHint", "כדי לזירה, גרור את הסמל המתאים מהלוח רכיבים לזירה."},
                {"TutorialLayer.SetFocusHint", "לשינוי נקודת עיגון המצלמה לחצו על לחצן הגדרת המוקד ולאחר מכן על כל רכיב או מקום בזירה."},
                {"TutorialLayer.ChangeColorHint", "השתמש בלחצן בחירת צבע על מנת להגדיר צבע עבור הרכיבים שנבחרו."},
                {"TutorialLayer.RotateHint", "כדי לסובב את הרכיבים הנבחרים, השתמש בלחצני הסיבוב. כל לחצן הצבוע בצבע אחר מסובב את הרכיב בכיוון שונה."},
                {"TutorialLayer.DeleteHint", "השתמש בלחצן זה כדי למחוק את הרכיבים הנבחרים מהזירה."},

                {"TutorialLayer.ZoomHint.Base", "כדי לקרב ולהרחיק את המצלמה השתמש" + " {0}."},
                {"TutorialLayer.ZoomHint.Wheel", "השתמש בגלגל של עכבר"},
                {"TutorialLayer.ZoomHint.Pinch", "באצבעות"},
                {"TutorialLayer.LinkedSelection", "הלחץ על רכיב והחזק כדי לבחור את כל החלקים הקשורים אליו."},

                {"ModelsSetsLayer.SetsNames.ModelsSets", "Models sets"},

                {"ModelsSetsLayer.SetsNames.KBigFigures", "Big Figures"},
                {"ModelsSetsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
                {"ModelsSetsLayer.SetsNames.Architectics", "Architectics"},
                {"ModelsSetsLayer.SetsNames.Geometrics", "Geometrics"},
                {"ModelsSetsLayer.SetsNames.Blasterology", "Blasterology"},
                {"ModelsSetsLayer.SetsNames.Militarics", "Militarics"},
                {"ModelsSetsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
                {"ModelsSetsLayer.SetsNames.Monsterology", "Monsterology"},
                {"ModelsSetsLayer.SetsNames.Robotology", "Robotology"},
                {"ModelsSetsLayer.SetsNames.Geometry", "Geometry"},
                {"ModelsSetsLayer.SetsNames.Architecture", "Architecture"},
                {"ModelsSetsLayer.SetsNames.Spaceships", "Spaceships"},
                {"ModelsSetsLayer.SetsNames.Playground", "Playground"},
                {"ModelsSetsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
                {"ModelsSetsLayer.SetsNames.Marine", "Marine"},
                {"ModelsSetsLayer.SetsNames.Aircraft", "Aircraft"},
                {"ModelsSetsLayer.SetsNames.Space", "Space"},
                {"ModelsSetsLayer.SetsNames.Mix", "Mix"},
                {"ModelsSetsLayer.SetsNames.Animals", "Animals"},
                {"ModelsSetsLayer.SetsNames.Flowers", "Flowers"},
                {"ModelsSetsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
                {"ModelsSetsLayer.SetsNames.BirdLama", "Bird-Lama"},
                {"ModelsSetsLayer.SetsNames.PlaneShip", "Plane-Ship"},
                {"ModelsSetsLayer.SetsNames.Butterflies", "Butterflies"},
                {"ModelsSetsLayer.SetsNames.Masks", "Masks"},
                {"ModelsSetsLayer.SetsNames.Racing", "Racing"},
                {"ModelsSetsLayer.SetsNames.RallyRade", "Rally Rade"},
                {"ModelsSetsLayer.SetsNames.Kids200", "Kids 200"},
                {"ModelsSetsLayer.SetsNames.Kids100", "Kids 100"},
                {"ModelsSetsLayer.SetsNames.Kids40", "Kids 40"},

                {"ModelsSetsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
                {"ModelsSetsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
                {"ModelsSetsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
                {"ModelsSetsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
                {"ModelsSetsLayer.ModelsNames.KingsCastle", "King's Castle"},
                {"ModelsSetsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
                {"ModelsSetsLayer.ModelsNames.SpaceLight", "Space Light"},
                {"ModelsSetsLayer.ModelsNames.Cube", "Cube"},
                {"ModelsSetsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
                {"ModelsSetsLayer.ModelsNames.Fractal", "Fractal"},
                {"ModelsSetsLayer.ModelsNames.Globe", "Globe"},
                {"ModelsSetsLayer.ModelsNames.Lattice", "Lattice"},
                {"ModelsSetsLayer.ModelsNames.Pyramid", "Pyramid"},
                {"ModelsSetsLayer.ModelsNames.Sphere", "Sphere"},
                {"ModelsSetsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
                {"ModelsSetsLayer.ModelsNames.Megablaster", "Megablaster"},
                {"ModelsSetsLayer.ModelsNames.Miniblaster", "Miniblaster"},
                {"ModelsSetsLayer.ModelsNames.Parablaster", "Parablaster"},
                {"ModelsSetsLayer.ModelsNames.Fighter", "Fighter"},
                {"ModelsSetsLayer.ModelsNames.Helicopter", "Helicopter"},
                {"ModelsSetsLayer.ModelsNames.Submarine", "Submarine"},
                {"ModelsSetsLayer.ModelsNames.Tank", "Tank"},
                {"ModelsSetsLayer.ModelsNames.Dachshund", "Dachshund"},
                {"ModelsSetsLayer.ModelsNames.Fawn", "Fawn"},
                {"ModelsSetsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
                {"ModelsSetsLayer.ModelsNames.SaurKing", "Saur King"},
                {"ModelsSetsLayer.ModelsNames.Tortilla", "Tortilla"},
                {"ModelsSetsLayer.ModelsNames.Triceratops", "Triceratops"},
                {"ModelsSetsLayer.ModelsNames.Bossmonster", "Bossmonster"},
                {"ModelsSetsLayer.ModelsNames.Cyclops", "Cyclops"},
                {"ModelsSetsLayer.ModelsNames.Monster", "Monster"},
                {"ModelsSetsLayer.ModelsNames.Radiomonster", "Radiomonster"},
                {"ModelsSetsLayer.ModelsNames.Smartmonster", "Smartmonster"},
                {"ModelsSetsLayer.ModelsNames.Stereomonster", "Stereomonster"},
                {"ModelsSetsLayer.ModelsNames.Telemonster", "Telemonster"},
                {"ModelsSetsLayer.ModelsNames.Threeclopes", "Threeclopes"},
                {"ModelsSetsLayer.ModelsNames.RobotAndroid", "Robot 1"},
                {"ModelsSetsLayer.ModelsNames.RobotTransformer", "Robot 4"},
                {"ModelsSetsLayer.ModelsNames.RobotFerreous", "Robot 2"},
                {"ModelsSetsLayer.ModelsNames.RobotQuadric", "Robot 3"},
                {"ModelsSetsLayer.ModelsNames.RollerRobot", "Roller Robot"},
                {"ModelsSetsLayer.ModelsNames.Crystal", "Crystal"},
                {"ModelsSetsLayer.ModelsNames.Hexanom", "Hexanom"},
                {"ModelsSetsLayer.ModelsNames.Neutron", "Neutron"},
                {"ModelsSetsLayer.ModelsNames.Prism", "Prism"},
                {"ModelsSetsLayer.ModelsNames.Spring", "Spring"},
                {"ModelsSetsLayer.ModelsNames.VectorTower", "Vector Tower"},
                {"ModelsSetsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
                {"ModelsSetsLayer.ModelsNames.FortRoyal", "Fort Royal"},
                {"ModelsSetsLayer.ModelsNames.Skyscraper", "Skyscraper"},
                {"ModelsSetsLayer.ModelsNames.Destroyer", "Destroyer"},
                {"ModelsSetsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
                {"ModelsSetsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
                {"ModelsSetsLayer.ModelsNames.SpacePike", "Space Pike"},
                {"ModelsSetsLayer.ModelsNames.TSpace", "TSpace"},
                {"ModelsSetsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
                {"ModelsSetsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
                {"ModelsSetsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
                {"ModelsSetsLayer.ModelsNames.Seesaw", "Seesaw"},
                {"ModelsSetsLayer.ModelsNames.Slide", "Slide"},
                {"ModelsSetsLayer.ModelsNames.Swing", "Swing"},
                {"ModelsSetsLayer.ModelsNames.Frusaur", "Frusaur"},
                {"ModelsSetsLayer.ModelsNames.Catamaran", "Catamaran"},
                {"ModelsSetsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
                {"ModelsSetsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
                {"ModelsSetsLayer.ModelsNames.Airplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.ControlTower", "Control Tower"},
                {"ModelsSetsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
                {"ModelsSetsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
                {"ModelsSetsLayer.ModelsNames.SpaceRadar", "Space Radar"},
                {"ModelsSetsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
                {"ModelsSetsLayer.ModelsNames.Babycopter", "Babycopter"},
                {"ModelsSetsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
                {"ModelsSetsLayer.ModelsNames.Giraffe", "Giraffe"},
                {"ModelsSetsLayer.ModelsNames.HandBridge", "Hand-bridge"},
                {"ModelsSetsLayer.ModelsNames.Plane", "Plane"},
                {"ModelsSetsLayer.ModelsNames.Robot", "Robot"},
                {"ModelsSetsLayer.ModelsNames.Tower", "Tower"},
                {"ModelsSetsLayer.ModelsNames.Umberflower", "Umberflower"},
                {"ModelsSetsLayer.ModelsNames.BabyPanda", "Baby Panda"},
                {"ModelsSetsLayer.ModelsNames.Doggie", "Doggie"},
                {"ModelsSetsLayer.ModelsNames.Lamb", "Lamb"},
                {"ModelsSetsLayer.ModelsNames.Dandelion", "Dandelion"},
                {"ModelsSetsLayer.ModelsNames.Lily", "Lily"},
                {"ModelsSetsLayer.ModelsNames.BabyDeer", "Baby Deer"},
                {"ModelsSetsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
                {"ModelsSetsLayer.ModelsNames.Birdy", "Birdy"},
                {"ModelsSetsLayer.ModelsNames.Lama", "Lama"},
                {"ModelsSetsLayer.ModelsNames.LittleShip", "Little Ship"},
                {"ModelsSetsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
                {"ModelsSetsLayer.ModelsNames.Swallowtail", "Swallowtail"},
                {"ModelsSetsLayer.ModelsNames.Moustashed", "Moustashed"},
                {"ModelsSetsLayer.ModelsNames.QuadBike", "Quad Bike"},
                {"ModelsSetsLayer.ModelsNames.RaceCar", "Race Car"},
                {"ModelsSetsLayer.ModelsNames.Buggy", "Buggy"},
                {"ModelsSetsLayer.ModelsNames.Motocycle", "Motocycle"},
                {"ModelsSetsLayer.ModelsNames.Tricycle", "Tricycle"},
                {"ModelsSetsLayer.ModelsNames.KidsAirplane", "Airplane"},
                {"ModelsSetsLayer.ModelsNames.KidsChair", "Chair"},
                {"ModelsSetsLayer.ModelsNames.KidsDragonfly", "Dragonfly"},
                {"ModelsSetsLayer.ModelsNames.KidsLodge", "Lodge"},
                {"ModelsSetsLayer.ModelsNames.KidsMan", "Little Man"},
                {"ModelsSetsLayer.ModelsNames.KidsPuppy", "Puppy"},
                {"ModelsSetsLayer.ModelsNames.KidsSpider", "Spider"},
                {"ModelsSetsLayer.ModelsNames.KidsTree", "Tree"},
                {"ModelsSetsLayer.ModelsNames.KidsTruck", "Truck"},
                {"ModelsSetsLayer.ModelsNames.KidsTruckCrane", "Truck Crane"},
                {"ModelsSetsLayer.ModelsNames.KidsVase", "Vase"},
                {"ModelsSetsLayer.ModelsNames.KidsBench", "Bench"},
                {"ModelsSetsLayer.ModelsNames.KidsTable", "Table"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 (1)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 (2)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 (3)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 (4)"},
                {"ModelsSetsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 (5)"},
                {"ModelsSetsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
                {"ModelsSetsLayer.ModelsNames.Unbreakable", "Unbreakable"},
                {"ModelsSetsLayer.ModelsNames.Logo", "Logo"},
            }
        };

        public static int Lang
        {
            get
            {
                if (_lang != -1)
                {
                    return _lang;
                }

                if (!PlayerPrefs.HasKey("Language"))
                {
                    int defaultLang;

                    switch (Application.systemLanguage)
                    {
                        case SystemLanguage.Russian:
                            defaultLang = 1;
                            break;
                        case SystemLanguage.German:
                            defaultLang = 2;
                            break;
                        case SystemLanguage.Polish:
                            defaultLang = 3;
                            break;
                        case SystemLanguage.Hebrew:
                            defaultLang = 4;
                            break;
                        default:
                            defaultLang = 0;
                            break;
                    }

                    PlayerPrefs.SetInt("Language", defaultLang);
                }

                _lang = PlayerPrefs.GetInt("Language");

                return _lang;
            }

            set
            {
                _lang = value;
                PlayerPrefs.SetInt("Language", value);
            }
        }
        private static int _lang = -1;

        public string TextKey;

        private Text _text;
        private bool _updateOnEnable; // чтобы RTL тексты отображались правильно,
        // их нужно передавать только в активные текстовые компоненты

        public void Awake()
        {
            AppController.Instance.LanguageChanged += SetLanguage;
        }

        public void Start()
        {
            SetLanguage(Lang);
        }

        protected void OnEnable()
        {
            if (!_updateOnEnable)
            {
                return;
            }

            SetLanguage(Lang);
            _updateOnEnable = false;
        }

        public void SetLanguage(int index)
        {
            if (_text == null)
            {

                _text = GetComponent<Text>();

                if (_text == null)
                {
                    Debug.LogError("Text component not found: " + gameObject.name);
                    return;
                }
            }

            if (!isActiveAndEnabled)
            {
                _updateOnEnable = true;
                return;
            }

            string newText;

            if (!Dictionaries[index].TryGetValue(TextKey, out newText))
            {
                Debug.LogError("Key " + TextKey + " not found in dictionary " + index);
                return;
            }

            _text.TextRespectingRtl(newText);
        }
    }
}
