
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Assets.Scripts
{

    //	public enum Languages
    //	{
    //		English,
    //		Russian,
    //	}

    public class UiLang : MonoBehaviour
    {

        //		public static readonly Dictionary<int, SystemLanguage>[] Lang2SystemLang = {
        //			new Dictionary<Languages, SystemLanguage>
        //			{
        //				{"EditorLayer.ActiveColor", "Active color"},
        //			}

        public static readonly Dictionary<string, string>[] Dictionaries = {
			new Dictionary<string, string>
			{
				{"EditorLayer.ActiveColor", "Active color"},
				{"EditorLayer.Details", "Elements"},

				{"Menu.Menu", "Menu"},
				{"Menu.NewScene", "New scene"},
				{"Menu.Save", "Save..."},
				{"Menu.Load", "Load..."},
				{"Menu.Export", "Export..."},
				{"Menu.SceneInfo", "Scene Info"},
				{"Menu.Demo", "Demo"},
				{"Menu.Help", "Help"},
				{"Menu.Exit", "Exit"},

				{"ModeSwitcher.Editor", "Editor mode"},
				{"ModeSwitcher.Instructions", "Instructions mode"},

				{"SceneInfoLayer.Copy", "Copy"},
				{"SceneInfoLayer.Height", "Height:"},
				{"SceneInfoLayer.Length", "Length:"},
				{"SceneInfoLayer.Width", "Width:"},
				{"SceneInfoLayer.Weight", "Weight:"},
				{"SceneInfoLayer.TotalDetails", "Total details:"},
				{"SceneInfoLayer.cm", "cm"},
				{"SceneInfoLayer.gram", "g"},

				{"SceneInfoLayer.Black", "Black"},
				{"SceneInfoLayer.Blue", "Blue"},
				{"SceneInfoLayer.Brown", "Brown"},
				{"SceneInfoLayer.Gray", "Gray"},
				{"SceneInfoLayer.Green", "Green"},
				{"SceneInfoLayer.Red", "Red"},
				{"SceneInfoLayer.White", "White"},
				{"SceneInfoLayer.Yellow", "Yellow"},

				{"SceneInfoLayer.BraceLineX2", "Brace Line (2x1): "},
				{"SceneInfoLayer.BraceLineX3", "Brace Line (3x1): "},
				{"SceneInfoLayer.BraceSquareX2", "Brace Square (2x1): "},
				{"SceneInfoLayer.BraceSquareX3", "Brace Square (3x1): "},
				{"SceneInfoLayer.Lego1x1", "Lego 1x1: "},
				{"SceneInfoLayer.Lego2x1", "Lego 2x1: "},
				{"SceneInfoLayer.Roll", "Roll: "},
				{"SceneInfoLayer.RailX2", "Rail: "},

				{"SceneInfoLayer.Axle1.0", "Axle 1.0: "},
				{"SceneInfoLayer.Axle2.0", "Axle 2.0: "},
				{"SceneInfoLayer.Axle2.5", "Axle 2.5: "},
				{"SceneInfoLayer.Axle3.0", "Axle 3.0: "},
				{"SceneInfoLayer.Axle3.5", "Axle 3.5: "},
				{"SceneInfoLayer.Axle8.0", "Axle 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Bevel Gear: "},
                {"SceneInfoLayer.AxleCoupling", "Coupling: "},
                {"SceneInfoLayer.AxleHub3x1", "Hub (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Hub (5x1): "},
                {"SceneInfoLayer.AxleTip", "Axle Tip: "},
                {"SceneInfoLayer.AxleWasher", "Washer: "},
                {"SceneInfoLayer.AxleWasherToothed", "Toothed Washer: "},
                {"SceneInfoLayer.AxleWheelBig", "Big Wheel: "},
                {"SceneInfoLayer.AxleWheelSmall", "Small Wheel: "},

				{"FileSelectionDialogLayer.SelectFile", "Select file..."},
				{"FileSelectionDialogLayer.EnterName", "Enter name..."},
				{"FileSelectionDialogLayer.Up", "Up"},
				{"FileSelectionDialogLayer.Downloads", "Downloads"},
				{"FileSelectionDialogLayer.Save", "Save"},
				{"FileSelectionDialogLayer.Cancel", "Cancel"},

				{"TutorialLayer.Next", "Next"},
				{"TutorialLayer.Welcome", "Welcome to\nFanclastic 3D Designer!\n\nThis program helps you to build Fanclastic models, view assembly instructions and create your own."},
				{"TutorialLayer.DetailsHint", "To add an element to the scene drag a corresponding icon from the elements' panel to the scene."},
				{"TutorialLayer.SetFocusHint", "To change camera anchor point click on the focus setting button and then on any element or spot on the scene."},
				{"TutorialLayer.ChangeColorHint", "Use the color select button to set a color for selected elements."},
				{"TutorialLayer.RotateHint", "To rotate selected elements use rotation buttons. Each button rotates elements around a drawn axis of a corresponding color."},
				{"TutorialLayer.DeleteHint", "Use this button to delete selected elements from the scene."},
				{"TutorialLayer.ZoomHint.Base", "Use {0} to zoom in and out the camera."},
				{"TutorialLayer.ZoomHint.Wheel", "mouse wheel"},
				{"TutorialLayer.ZoomHint.Pinch", "pinch"},
				{"TutorialLayer.LinkedSelection", "Click on an element and hold to select all linked parts."},

				{"DemoModelsLayer.SetsNames.BigFigures", "Big Figures"},
				{"DemoModelsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
				{"DemoModelsLayer.SetsNames.Architectics", "Architectics"},
				{"DemoModelsLayer.SetsNames.Geometrics", "Geometrics"},
				{"DemoModelsLayer.SetsNames.Blasterology", "Blasterology"},
				{"DemoModelsLayer.SetsNames.Militarics", "Militarics"},
				{"DemoModelsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
				{"DemoModelsLayer.SetsNames.Monsterology", "Monsterology"},
				{"DemoModelsLayer.SetsNames.Robotology", "Robotology"},
				{"DemoModelsLayer.SetsNames.Geometry", "Geometry"},
				{"DemoModelsLayer.SetsNames.Architecture", "Architecture"},
				{"DemoModelsLayer.SetsNames.Spaceships", "Spaceships"},
				{"DemoModelsLayer.SetsNames.Playground", "Playground"},
				{"DemoModelsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
				{"DemoModelsLayer.SetsNames.Marine", "Marine"},
				{"DemoModelsLayer.SetsNames.Aircraft", "Aircraft"},
				{"DemoModelsLayer.SetsNames.Space", "Space"},
				{"DemoModelsLayer.SetsNames.Mix", "Mix"},
				{"DemoModelsLayer.SetsNames.Animals", "Animals"},
				{"DemoModelsLayer.SetsNames.Flowers", "Flowers"},
				{"DemoModelsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
				{"DemoModelsLayer.SetsNames.BirdLama", "Bird-Lama"},
				{"DemoModelsLayer.SetsNames.PlaneShip", "Plane-Ship"},
				{"DemoModelsLayer.SetsNames.Butterflies", "Butterflies"},
				{"DemoModelsLayer.SetsNames.Masks", "Masks"},
				{"DemoModelsLayer.SetsNames.Racing", "Racing"},
				{"DemoModelsLayer.SetsNames.RallyRade", "Rally Rade"},

				{"DemoModelsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
				{"DemoModelsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
				{"DemoModelsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
				{"DemoModelsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
				{"DemoModelsLayer.ModelsNames.KingsCastle", "King's Castle"},
				{"DemoModelsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
				{"DemoModelsLayer.ModelsNames.SpaceLight", "Space Light"},
				{"DemoModelsLayer.ModelsNames.Cube", "Cube"},
				{"DemoModelsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
				{"DemoModelsLayer.ModelsNames.Fractal", "Fractal"},
				{"DemoModelsLayer.ModelsNames.Globe", "Globe"},
				{"DemoModelsLayer.ModelsNames.Lattice", "Lattice"},
				{"DemoModelsLayer.ModelsNames.Pyramid", "Pyramid"},
				{"DemoModelsLayer.ModelsNames.Sphere", "Sphere"},
				{"DemoModelsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
				{"DemoModelsLayer.ModelsNames.Megablaster", "Megablaster"},
				{"DemoModelsLayer.ModelsNames.Miniblaster", "Miniblaster"},
				{"DemoModelsLayer.ModelsNames.Parablaster", "Parablaster"},
				{"DemoModelsLayer.ModelsNames.Fighter", "Fighter"},
				{"DemoModelsLayer.ModelsNames.Helicopter", "Helicopter"},
				{"DemoModelsLayer.ModelsNames.Submarine", "Submarine"},
				{"DemoModelsLayer.ModelsNames.Tank", "Tank"},
				{"DemoModelsLayer.ModelsNames.Dachshund", "Dachshund"},
				{"DemoModelsLayer.ModelsNames.Fawn", "Fawn"},
				{"DemoModelsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
				{"DemoModelsLayer.ModelsNames.SaurKing", "Saur King"},
				{"DemoModelsLayer.ModelsNames.Tortilla", "Tortilla"},
				{"DemoModelsLayer.ModelsNames.Triceratops", "Triceratops"},
				{"DemoModelsLayer.ModelsNames.Bossmonster", "Bossmonster"},
				{"DemoModelsLayer.ModelsNames.Cyclops", "Cyclops"},
				{"DemoModelsLayer.ModelsNames.Monster", "Monster"},
				{"DemoModelsLayer.ModelsNames.Radiomonster", "Radiomonster"},
				{"DemoModelsLayer.ModelsNames.Smartmonster", "Smartmonster"},
				{"DemoModelsLayer.ModelsNames.Stereomonster", "Stereomonster"},
				{"DemoModelsLayer.ModelsNames.Telemonster", "Telemonster"},
				{"DemoModelsLayer.ModelsNames.Threeclopes", "Threeclopes"},
				{"DemoModelsLayer.ModelsNames.Robot_1", "Robot 1"},
				{"DemoModelsLayer.ModelsNames.Robot_2", "Robot 2"},
				{"DemoModelsLayer.ModelsNames.Robot_3", "Robot 3"},
				{"DemoModelsLayer.ModelsNames.Robot_4", "Robot 4"},
				{"DemoModelsLayer.ModelsNames.RollerRobot", "Roller Robot"},
				{"DemoModelsLayer.ModelsNames.Crystal", "Crystal"},
				{"DemoModelsLayer.ModelsNames.Hexanom", "Hexanom"},
				{"DemoModelsLayer.ModelsNames.Neutron", "Neutron"},
				{"DemoModelsLayer.ModelsNames.Prism", "Prism"},
				{"DemoModelsLayer.ModelsNames.Spring", "Spring"},
				{"DemoModelsLayer.ModelsNames.VectorTower", "Vector Tower"},
				{"DemoModelsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
				{"DemoModelsLayer.ModelsNames.FortRoyal", "Fort Royal"},
				{"DemoModelsLayer.ModelsNames.Skyscraper", "Skyscraper"},
				{"DemoModelsLayer.ModelsNames.Destroyer", "Destroyer"},
				{"DemoModelsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
				{"DemoModelsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
				{"DemoModelsLayer.ModelsNames.SpacePike", "Space Pike"},
				{"DemoModelsLayer.ModelsNames.TSpace", "TSpace"},
				{"DemoModelsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
				{"DemoModelsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
				{"DemoModelsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
				{"DemoModelsLayer.ModelsNames.Seesaw", "Seesaw"},
				{"DemoModelsLayer.ModelsNames.Slide", "Slide"},
				{"DemoModelsLayer.ModelsNames.Swing", "Swing"},
				{"DemoModelsLayer.ModelsNames.Frusaur", "Frusaur"},
				{"DemoModelsLayer.ModelsNames.Catamaran", "Catamaran"},
				{"DemoModelsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
				{"DemoModelsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
				{"DemoModelsLayer.ModelsNames.Airplane", "Airplane"},
				{"DemoModelsLayer.ModelsNames.ControlTower", "Control Tower"},
				{"DemoModelsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
				{"DemoModelsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
				{"DemoModelsLayer.ModelsNames.SpaceRadar", "Space Radar"},
				{"DemoModelsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
				{"DemoModelsLayer.ModelsNames.Babycopter", "Babycopter"},
				{"DemoModelsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
				{"DemoModelsLayer.ModelsNames.Giraffe", "Giraffe"},
				{"DemoModelsLayer.ModelsNames.HandBridge", "Hand-bridge"},
				{"DemoModelsLayer.ModelsNames.Plane", "Plane"},
				{"DemoModelsLayer.ModelsNames.Robot", "Robot"},
				{"DemoModelsLayer.ModelsNames.Tower", "Tower"},
				{"DemoModelsLayer.ModelsNames.Umberflower", "Umberflower"},
				{"DemoModelsLayer.ModelsNames.BabyPanda", "Baby Panda"},
				{"DemoModelsLayer.ModelsNames.Doggie", "Doggie"},
				{"DemoModelsLayer.ModelsNames.Lamb", "Lamb"},
				{"DemoModelsLayer.ModelsNames.Dandelion", "Dandelion"},
				{"DemoModelsLayer.ModelsNames.Lily", "Lily"},
				{"DemoModelsLayer.ModelsNames.BabyDeer", "Baby Deer"},
				{"DemoModelsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
				{"DemoModelsLayer.ModelsNames.Birdy", "Birdy"},
				{"DemoModelsLayer.ModelsNames.Lama", "Lama"},
				{"DemoModelsLayer.ModelsNames.LittleShip", "Little Ship"},
				{"DemoModelsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
				{"DemoModelsLayer.ModelsNames.Swallowtail", "Swallowtail"},
				{"DemoModelsLayer.ModelsNames.Moustashed", "Moustashed"},
				{"DemoModelsLayer.ModelsNames.QuadBike", "Quad Bike"},
				{"DemoModelsLayer.ModelsNames.RaceCar", "Race Car"},
				{"DemoModelsLayer.ModelsNames.Buggy", "Buggy"},
				{"DemoModelsLayer.ModelsNames.Motocycle", "Motocycle"},
				{"DemoModelsLayer.ModelsNames.Tricycle", "Tricycle"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 3"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 4"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 5"},
				{"DemoModelsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
				{"DemoModelsLayer.ModelsNames.Unbreakable", "Unbreakable"},
				{"DemoModelsLayer.ModelsNames.F", "F"},
			}, 
			new Dictionary<string, string>
			{
				{"EditorLayer.ActiveColor", "Активный цвет"},
				{"EditorLayer.Details", "Детали"},

				{"Menu.Menu", "Меню"},
				{"Menu.NewScene", "Новая сцена"},
				{"Menu.Save", "Сохранить..."},
				{"Menu.Load", "Загрузить..."},
				{"Menu.Export", "Экспорт..."},
				{"Menu.SceneInfo", "Инфо сцены"},
				{"Menu.Demo", "Демо"},
				{"Menu.Help", "Помощь"},
				{"Menu.Exit", "Выход"},

				{"ModeSwitcher.Editor", "Редактор"},
				{"ModeSwitcher.Instructions", "Инструкции"},

				{"SceneInfoLayer.Copy", "Копир."},
				{"SceneInfoLayer.Height", "Высота:"},
				{"SceneInfoLayer.Length", "Длина:"},
				{"SceneInfoLayer.Width", "Ширина:"},
				{"SceneInfoLayer.Weight", "Вес:"},
				{"SceneInfoLayer.TotalDetails", "Всего деталей:"},
				{"SceneInfoLayer.cm", "см"},
				{"SceneInfoLayer.gram", "г"},

				{"SceneInfoLayer.Black", "Черный"},
				{"SceneInfoLayer.Blue", "Синий"},
				{"SceneInfoLayer.Brown", "Коричневый"},
				{"SceneInfoLayer.Gray", "Серый"},
				{"SceneInfoLayer.Green", "Зеленый"},
				{"SceneInfoLayer.Red", "Красный"},
				{"SceneInfoLayer.White", "Белый"},
				{"SceneInfoLayer.Yellow", "Желтый"},

				{"SceneInfoLayer.Axle1.0", "Ось 1.0: "},
				{"SceneInfoLayer.Axle2.0", "Ось 2.0: "},
				{"SceneInfoLayer.Axle2.5", "Ось 2.5: "},
				{"SceneInfoLayer.Axle3.0", "Ось 3.0: "},
				{"SceneInfoLayer.Axle3.5", "Ось 3.5: "},
				{"SceneInfoLayer.Axle8.0", "Ось 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Конусная шестеренка: "},
                {"SceneInfoLayer.AxleCoupling", "Муфта: "},
                {"SceneInfoLayer.AxleHub3x1", "Ступица (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Ступица (5x1): "},
                {"SceneInfoLayer.AxleTip", "Осевой наконечник: "},
                {"SceneInfoLayer.AxleWasher", "Шайба: "},
                {"SceneInfoLayer.AxleWasherToothed", "Зубчатая шайба: "},
                {"SceneInfoLayer.AxleWheelBig", "Большое колесо: "},
                {"SceneInfoLayer.AxleWheelSmall", "Малое колесо: "},

				{"SceneInfoLayer.BraceLineX2", "Скобка тонкая (2x1): "},
				{"SceneInfoLayer.BraceLineX3", "Скобка тонкая (3x1): "},
				{"SceneInfoLayer.BraceSquareX2", "Скобка квадратная (2x1): "},
				{"SceneInfoLayer.BraceSquareX3", "Скобка квадратная (3x1): "},
				{"SceneInfoLayer.Lego1x1", "Лего 1x1: "},
				{"SceneInfoLayer.Lego2x1", "Лего 2x1: "},
				{"SceneInfoLayer.Roll", "Валик: "},
				{"SceneInfoLayer.RailX2", "Рельса: "},

				{"FileSelectionDialogLayer.SelectFile", "Выберите файл..."},
				{"FileSelectionDialogLayer.EnterName", "Введите имя..."},
				{"FileSelectionDialogLayer.Up", "Наверх"},
				{"FileSelectionDialogLayer.Downloads", "Загрузки"},
				{"FileSelectionDialogLayer.Save", "Сохран."},
				{"FileSelectionDialogLayer.Cancel", "Отмена"},

				{"TutorialLayer.Next", "Далее"},
				{"TutorialLayer.Welcome", "Добро пожаловать в\nFanclastic 3D Designer!\n\nВ этой программе вы можете строить модели из конструктора Fanclastic, просматривать инструкции по сборке и создавать свои собственные!"},
				{"TutorialLayer.DetailsHint", "Чтобы добавить на сцену новую деталь, перетащите соответствующую иконку с панели деталей на сцену."},
				{"TutorialLayer.SetFocusHint", "Чтобы изменить точку привязки камеры, нажмите на кнопку установки фокуса, а затем на любую деталь или точку на сцене."},
				{"TutorialLayer.ChangeColorHint", "Используйте кнопку выбора цвета, чтобы задать цвет выделенным деталям."},
				{"TutorialLayer.RotateHint", "Для поворота выделенных деталей в пространстве используйте кнопки поворота. Каждая кнопка поворачивает детали вокруг нарисованной оси соответствующего цвета."},
				{"TutorialLayer.DeleteHint", "Используйте эту кнопку, чтобы удалить выделенные детали со сцены."},
				{"TutorialLayer.ZoomHint.Base", "Используйте {0}, чтобы приблизить или удалить камеру."},
				{"TutorialLayer.ZoomHint.Wheel", "колесо мыши"},
				{"TutorialLayer.ZoomHint.Pinch", "жест двумя пальцами"},
				{"TutorialLayer.LinkedSelection", "Нажмите на деталь и удерживайте, чтобы выделить одновременно все связанные с ней детали."},
				
				{"DemoModelsLayer.SetsNames.BigFigures", "Большие модели"},
				{"DemoModelsLayer.SetsNames.Cosmoclastics", "Космокластика"},
				{"DemoModelsLayer.SetsNames.Architectics", "Архитектика"},
				{"DemoModelsLayer.SetsNames.Geometrics", "Геометрика"},
				{"DemoModelsLayer.SetsNames.Blasterology", "Бластерология"},
				{"DemoModelsLayer.SetsNames.Militarics", "Милитэрика"},
				{"DemoModelsLayer.SetsNames.Zoosaurics", "Зоозаврика"},
				{"DemoModelsLayer.SetsNames.Monsterology", "Монстроведение"},
				{"DemoModelsLayer.SetsNames.Robotology", "Роботоводство"},
				{"DemoModelsLayer.SetsNames.Geometry", "Геометрия"},
				{"DemoModelsLayer.SetsNames.Architecture", "Архитектура"},
				{"DemoModelsLayer.SetsNames.Spaceships", "Звездолеты"},
				{"DemoModelsLayer.SetsNames.Playground", "Десткая площадка"},
				{"DemoModelsLayer.SetsNames.Dinosaurs", "Динозавры"},
				{"DemoModelsLayer.SetsNames.Marine", "Морской"},
				{"DemoModelsLayer.SetsNames.Aircraft", "Воздушные суда"},
				{"DemoModelsLayer.SetsNames.Space", "Космос"},
				{"DemoModelsLayer.SetsNames.Mix", "Микс"},
				{"DemoModelsLayer.SetsNames.Animals", "Животные"},
				{"DemoModelsLayer.SetsNames.Flowers", "Цветы"},
				{"DemoModelsLayer.SetsNames.DeerGiraff", "Олень-Жираф"},
				{"DemoModelsLayer.SetsNames.BirdLama", "Птичка-Лама"},
				{"DemoModelsLayer.SetsNames.PlaneShip", "Самолет-Кораблик"},
				{"DemoModelsLayer.SetsNames.Butterflies", "Бабочки"},
				{"DemoModelsLayer.SetsNames.Masks", "Маски"},
				{"DemoModelsLayer.SetsNames.Racing", "Гонки"},
				{"DemoModelsLayer.SetsNames.RallyRade", "Ралли"},

				{"DemoModelsLayer.ModelsNames.GiraffeGulliver", "Жираф Гулливер"},
				{"DemoModelsLayer.ModelsNames.DeltaSpaceship", "Дельта"},
				{"DemoModelsLayer.ModelsNames.InfinitySpaceship", "Инфинити"},
				{"DemoModelsLayer.ModelsNames.OmegaSpaceship", "Омега"},
				{"DemoModelsLayer.ModelsNames.KingsCastle", "Королевский замок"},
				{"DemoModelsLayer.ModelsNames.SkySpearTower", "Башня Небесное копьё"},
				{"DemoModelsLayer.ModelsNames.SpaceLight", "Космический маяк"},
				{"DemoModelsLayer.ModelsNames.Cube", "Куб"},
				{"DemoModelsLayer.ModelsNames.FlexibleStick", "Изгибалочка"},
				{"DemoModelsLayer.ModelsNames.Fractal", "Фрактал"},
				{"DemoModelsLayer.ModelsNames.Globe", "Глобус"},
				{"DemoModelsLayer.ModelsNames.Lattice", "Решетка"},
				{"DemoModelsLayer.ModelsNames.Pyramid", "Пирамида"},
				{"DemoModelsLayer.ModelsNames.Sphere", "Сфера"},
				{"DemoModelsLayer.ModelsNames.Hyperblaster", "Гипербластер"},
				{"DemoModelsLayer.ModelsNames.Megablaster", "Мегабластер"},
				{"DemoModelsLayer.ModelsNames.Miniblaster", "Минибластер"},
				{"DemoModelsLayer.ModelsNames.Parablaster", "Парабластер"},
				{"DemoModelsLayer.ModelsNames.Fighter", "Истребитель"},
				{"DemoModelsLayer.ModelsNames.Helicopter", "Вертолет"},
				{"DemoModelsLayer.ModelsNames.Submarine", "Батискаф"},
				{"DemoModelsLayer.ModelsNames.Tank", "Танк"},
				{"DemoModelsLayer.ModelsNames.Dachshund", "Такса"},
				{"DemoModelsLayer.ModelsNames.Fawn", "Олененок"},
				{"DemoModelsLayer.ModelsNames.GiraffeKid", "Жирафик"},
				{"DemoModelsLayer.ModelsNames.SaurKing", "Король Завр"},
				{"DemoModelsLayer.ModelsNames.Tortilla", "Черепаха"},
				{"DemoModelsLayer.ModelsNames.Triceratops", "Трицератопс"},
				{"DemoModelsLayer.ModelsNames.Bossmonster", "Боссмонстрик"},
				{"DemoModelsLayer.ModelsNames.Cyclops", "Циклоп"},
				{"DemoModelsLayer.ModelsNames.Monster", "Монстрозаврик"},
				{"DemoModelsLayer.ModelsNames.Radiomonster", "Радиомонстрик"},
				{"DemoModelsLayer.ModelsNames.Smartmonster", "Смартмонстрик"},
				{"DemoModelsLayer.ModelsNames.Stereomonster", "Стереомонстрик"},
				{"DemoModelsLayer.ModelsNames.Telemonster", "Телемонстрик"},
				{"DemoModelsLayer.ModelsNames.Threeclopes", "Триклоп"},
				{"DemoModelsLayer.ModelsNames.Robot_1", "Робот 1"},
				{"DemoModelsLayer.ModelsNames.Robot_2", "Робот 2"},
				{"DemoModelsLayer.ModelsNames.Robot_3", "Робот 3"},
				{"DemoModelsLayer.ModelsNames.Robot_4", "Робот 4"},
				{"DemoModelsLayer.ModelsNames.RollerRobot", "Роллер"},
				{"DemoModelsLayer.ModelsNames.Crystal", "Кристалл"},
				{"DemoModelsLayer.ModelsNames.Hexanom", "Гексаном"},
				{"DemoModelsLayer.ModelsNames.Neutron", "Нейтрон"},
				{"DemoModelsLayer.ModelsNames.Prism", "Призма"},
				{"DemoModelsLayer.ModelsNames.Spring", "Пружинка"},
				{"DemoModelsLayer.ModelsNames.VectorTower", "Башня Вектор"},
				{"DemoModelsLayer.ModelsNames.ArrowTower", "Башня Стрела"},
				{"DemoModelsLayer.ModelsNames.FortRoyal", "Крепость"},
				{"DemoModelsLayer.ModelsNames.Skyscraper", "Небоскрёб"},
				{"DemoModelsLayer.ModelsNames.Destroyer", "Разрушитель"},
				{"DemoModelsLayer.ModelsNames.GlitchSender", "Шумотрон"},
				{"DemoModelsLayer.ModelsNames.SpaceIntruder", "Космическая ищейка"},
				{"DemoModelsLayer.ModelsNames.SpacePike", "Пик Космос"},
				{"DemoModelsLayer.ModelsNames.TSpace", "Т-Космос"},
				{"DemoModelsLayer.ModelsNames.CarouselTower", "Башня Каруселька	"},
				{"DemoModelsLayer.ModelsNames.JumpingBalance", "Балансир Лягушка"},
				{"DemoModelsLayer.ModelsNames.MerryGoRound", "Карусель"},
				{"DemoModelsLayer.ModelsNames.Seesaw", "Качалка"},
				{"DemoModelsLayer.ModelsNames.Slide", "Горка"},
				{"DemoModelsLayer.ModelsNames.Swing", "Качели"},
				{"DemoModelsLayer.ModelsNames.Frusaur", "Фрузавр"},
				{"DemoModelsLayer.ModelsNames.Catamaran", "Катамаран"},
				{"DemoModelsLayer.ModelsNames.FairWindShip", "Бригантина"},
				{"DemoModelsLayer.ModelsNames.SeaLightTower", "Сигнальная башня"},
				{"DemoModelsLayer.ModelsNames.Airplane", "Самолет"},
				{"DemoModelsLayer.ModelsNames.ControlTower", "Диспетчерская вышка"},
				{"DemoModelsLayer.ModelsNames.FieryRocket", "Огненная ракета"},
				{"DemoModelsLayer.ModelsNames.GammaRayDestroyer", "Истребитель Гамма"},
				{"DemoModelsLayer.ModelsNames.SpaceRadar", "Космический радар"},
				{"DemoModelsLayer.ModelsNames.StrikeFighterVolcano", "Штурмовик Вулкан"},
				{"DemoModelsLayer.ModelsNames.Babycopter", "Вертолёт"},
				{"DemoModelsLayer.ModelsNames.DragonflyPlane", "Стреколёт"},
				{"DemoModelsLayer.ModelsNames.Giraffe", "Жираф"},
				{"DemoModelsLayer.ModelsNames.HandBridge", "Переностик"},
				{"DemoModelsLayer.ModelsNames.Plane", "Самолёт"},
				{"DemoModelsLayer.ModelsNames.Robot", "Робот"},
				{"DemoModelsLayer.ModelsNames.Tower", "Башня"},
				{"DemoModelsLayer.ModelsNames.Umberflower", "Зонтоцветик"},
				{"DemoModelsLayer.ModelsNames.BabyPanda", "Панда"},
				{"DemoModelsLayer.ModelsNames.Doggie", "Пёсик"},
				{"DemoModelsLayer.ModelsNames.Lamb", "Овечка"},
				{"DemoModelsLayer.ModelsNames.Dandelion", "Одуванчик"},
				{"DemoModelsLayer.ModelsNames.Lily", "Лилия"},
				{"DemoModelsLayer.ModelsNames.BabyDeer", "Олень"},
				{"DemoModelsLayer.ModelsNames.BabyGiraffe", "Жираф"},
				{"DemoModelsLayer.ModelsNames.Birdy", "Птичка"},
				{"DemoModelsLayer.ModelsNames.Lama", "Лама"},
				{"DemoModelsLayer.ModelsNames.LittleShip", "Кораблик"},
				{"DemoModelsLayer.ModelsNames.Hawkmoth", "Бражник"},
				{"DemoModelsLayer.ModelsNames.Swallowtail", "Махаон"},
				{"DemoModelsLayer.ModelsNames.Moustashed", "Усач"},
				{"DemoModelsLayer.ModelsNames.QuadBike", "Квадроцикл"},
				{"DemoModelsLayer.ModelsNames.RaceCar", "Болид"},
				{"DemoModelsLayer.ModelsNames.Buggy", "Багги"},
				{"DemoModelsLayer.ModelsNames.Motocycle", "Мотоцикл"},
				{"DemoModelsLayer.ModelsNames.Tricycle", "Трицикл"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(1)", "Решётка 3x3 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(2)", "Решётка 3x3 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(1)", "Решётка 6x2 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(2)", "Решётка 6x2 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(3)", "Решётка 6x2 3"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(4)", "Решётка 6x2 4"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(5)", "Решётка 6x2 5"},
				{"DemoModelsLayer.ModelsNames.Tetrahedron", "Тетраэдр"},
				{"DemoModelsLayer.ModelsNames.Unbreakable", "Нерушимая"},
				{"DemoModelsLayer.ModelsNames.F", "F"},
			},
			new Dictionary<string, string>
			{
				{"EditorLayer.ActiveColor", "Aktive Farbe"},
				{"EditorLayer.Details", "Details"},

				{"Menu.Menu", "Menü"},
				{"Menu.NewScene", "Neue Szene"},
				{"Menu.Save", "Speichern..."},
				{"Menu.Load", "Herunterladen..."},
				{"Menu.Export", "Export..."},
				{"Menu.SceneInfo", "Szenen info"},
				{"Menu.Demo", "Demo"},
				{"Menu.Help", "Hilfe"},
				{"Menu.Exit", "Beenden"},

				{"ModeSwitcher.Editor", "Editor"},
				{"ModeSwitcher.Instructions", "Anleitungen"},

				{"SceneInfoLayer.Copy", "Kopieren"},
				{"SceneInfoLayer.Height", "Höhe:"},
				{"SceneInfoLayer.Length", "Länge:"},
				{"SceneInfoLayer.Width", "Breite:"},
				{"SceneInfoLayer.Weight", "Gewicht:"},
				{"SceneInfoLayer.TotalDetails", "Gesamtzahl der Details"},
				{"SceneInfoLayer.cm", "cm"},
				{"SceneInfoLayer.gram", "g"},

				{"SceneInfoLayer.Black", "Schwarz"},
				{"SceneInfoLayer.Blue", "Blau"},
				{"SceneInfoLayer.Brown", "Braun"},
				{"SceneInfoLayer.Gray", "Grau"},
				{"SceneInfoLayer.Green", "Grün"},
				{"SceneInfoLayer.Red", "Rot"},
				{"SceneInfoLayer.White", "Weiß"},
				{"SceneInfoLayer.Yellow", "Gelb"},

				{"SceneInfoLayer.BraceLineX2", "Dünne Klammer (2x1): "},
				{"SceneInfoLayer.BraceLineX3", "Dünne Klammer (3x1): "},
				{"SceneInfoLayer.BraceSquareX2", "Quadratische Klammer (2x1): "},
				{"SceneInfoLayer.BraceSquareX3", "Quadratische Klammer (3x1): "},
				{"SceneInfoLayer.Lego1x1", "Lego 1x1: "},
				{"SceneInfoLayer.Lego2x1", "Lego 2x1: "},
				{"SceneInfoLayer.Roll", "Rolle: "},
				{"SceneInfoLayer.RailX2", "Schiene: "},

				{"SceneInfoLayer.Axle1.0", "Achse 1.0: "},
				{"SceneInfoLayer.Axle2.0", "Achse 2.0: "},
				{"SceneInfoLayer.Axle2.5", "Achse 2.5: "},
				{"SceneInfoLayer.Axle3.0", "Achse 3.0: "},
				{"SceneInfoLayer.Axle3.5", "Achse 3.5: "},
				{"SceneInfoLayer.Axle8.0", "Achse 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Kegelradgetriebe: "},
                {"SceneInfoLayer.AxleCoupling", "Kupplung: "},
                {"SceneInfoLayer.AxleHub3x1", "Nabe (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Nabe (5x1): "},
                {"SceneInfoLayer.AxleTip", "Spitze: "},
                {"SceneInfoLayer.AxleWasher", "Scheibe: "},
                {"SceneInfoLayer.AxleWasherToothed", "Zahnscheibe: "},
                {"SceneInfoLayer.AxleWheelBig", "Großes Rad: "},
                {"SceneInfoLayer.AxleWheelSmall", "Kleines Rad: "},

				{"FileSelectionDialogLayer.SelectFile", "Datei auswählen..."},
				{"FileSelectionDialogLayer.EnterName", "Namen eingeben..."},
				{"FileSelectionDialogLayer.Up", "Nach oben "},
				{"FileSelectionDialogLayer.Downloads", "Herunterladen"},
				{"FileSelectionDialogLayer.Save", "Speichern"},
				{"FileSelectionDialogLayer.Cancel", "Abbrechen"},

				{"TutorialLayer.Next", "Nächster"},
				{"TutorialLayer.Welcome", "Willkommen bei\nFanclastic 3D Designer!\n\nIn diesem Programm können Sie Modelle aus dem Fanclastic-Baukasten erstellen, Bauanleitungen ansehen und eigene erstellen!"},
				{"TutorialLayer.DetailsHint", "Um der Szene ein neues Detail hinzuzufügen, ziehen Sie das entsprechende Symbol aus der Detail-Palette in die Szene"},
				{"TutorialLayer.SetFocusHint", "Um den Fangpunkt der Kamera zu ändern, klicken Sie auf die Schaltfläche für die Fokuseinstellung und dann auf jeden Punkt oder jedes Detail auf der Bühne.."},
				{"TutorialLayer.ChangeColorHint", "Verwenden Sie die Farbauswahltaste, um die Farbe für die markierten Elemente festzulegen."},
				{"TutorialLayer.RotateHint", "Verwenden Sie die Drehschaltflächen, um die ausgewählten Details im Raum zu drehen. Jede Schaltfläche dreht die Details um die gezeichnete Achse der entsprechenden Farbe."},
				{"TutorialLayer.DeleteHint", "Verwenden Sie diese Schaltfläche, um ausgewählte Details aus der Szene zu löschen.."},
				{"TutorialLayer.ZoomHint.Base", "Verwenden Sie {0}, um die Kamera zu vergrößern oder zu verkleinern."},
				{"TutorialLayer.ZoomHint.Wheel", "Mausrad"},
				{"TutorialLayer.ZoomHint.Pinch", "Zwei-Finger-Geste"},
				{"TutorialLayer.LinkedSelection", "Klicken Sie auf das Detail und halten Sie es gedrückt, um alle zugehörigen Details gleichzeitig auszuwählen."},

				{"DemoModelsLayer.SetsNames.BigFigures", "Big Figures"},
				{"DemoModelsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
				{"DemoModelsLayer.SetsNames.Architectics", "Architectics"},
				{"DemoModelsLayer.SetsNames.Geometrics", "Geometrics"},
				{"DemoModelsLayer.SetsNames.Blasterology", "Blasterology"},
				{"DemoModelsLayer.SetsNames.Militarics", "Militarics"},
				{"DemoModelsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
				{"DemoModelsLayer.SetsNames.Monsterology", "Monsterology"},
				{"DemoModelsLayer.SetsNames.Robotology", "Robotology"},
				{"DemoModelsLayer.SetsNames.Geometry", "Geometry"},
				{"DemoModelsLayer.SetsNames.Architecture", "Architecture"},
				{"DemoModelsLayer.SetsNames.Spaceships", "Spaceships"},
				{"DemoModelsLayer.SetsNames.Playground", "Playground"},
				{"DemoModelsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
				{"DemoModelsLayer.SetsNames.Marine", "Marine"},
				{"DemoModelsLayer.SetsNames.Aircraft", "Aircraft"},
				{"DemoModelsLayer.SetsNames.Space", "Space"},
				{"DemoModelsLayer.SetsNames.Mix", "Mix"},
				{"DemoModelsLayer.SetsNames.Animals", "Animals"},
				{"DemoModelsLayer.SetsNames.Flowers", "Flowers"},
				{"DemoModelsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
				{"DemoModelsLayer.SetsNames.BirdLama", "Bird-Lama"},
				{"DemoModelsLayer.SetsNames.PlaneShip", "Plane-Ship"},
				{"DemoModelsLayer.SetsNames.Butterflies", "Butterflies"},
				{"DemoModelsLayer.SetsNames.Masks", "Masks"},
				{"DemoModelsLayer.SetsNames.Racing", "Racing"},
				{"DemoModelsLayer.SetsNames.RallyRade", "Rally Rade"},

				{"DemoModelsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
				{"DemoModelsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
				{"DemoModelsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
				{"DemoModelsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
				{"DemoModelsLayer.ModelsNames.KingsCastle", "King's Castle"},
				{"DemoModelsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
				{"DemoModelsLayer.ModelsNames.SpaceLight", "Space Light"},
				{"DemoModelsLayer.ModelsNames.Cube", "Cube"},
				{"DemoModelsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
				{"DemoModelsLayer.ModelsNames.Fractal", "Fractal"},
				{"DemoModelsLayer.ModelsNames.Globe", "Globe"},
				{"DemoModelsLayer.ModelsNames.Lattice", "Lattice"},
				{"DemoModelsLayer.ModelsNames.Pyramid", "Pyramid"},
				{"DemoModelsLayer.ModelsNames.Sphere", "Sphere"},
				{"DemoModelsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
				{"DemoModelsLayer.ModelsNames.Megablaster", "Megablaster"},
				{"DemoModelsLayer.ModelsNames.Miniblaster", "Miniblaster"},
				{"DemoModelsLayer.ModelsNames.Parablaster", "Parablaster"},
				{"DemoModelsLayer.ModelsNames.Fighter", "Fighter"},
				{"DemoModelsLayer.ModelsNames.Helicopter", "Helicopter"},
				{"DemoModelsLayer.ModelsNames.Submarine", "Submarine"},
				{"DemoModelsLayer.ModelsNames.Tank", "Tank"},
				{"DemoModelsLayer.ModelsNames.Dachshund", "Dachshund"},
				{"DemoModelsLayer.ModelsNames.Fawn", "Fawn"},
				{"DemoModelsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
				{"DemoModelsLayer.ModelsNames.SaurKing", "Saur King"},
				{"DemoModelsLayer.ModelsNames.Tortilla", "Tortilla"},
				{"DemoModelsLayer.ModelsNames.Triceratops", "Triceratops"},
				{"DemoModelsLayer.ModelsNames.Bossmonster", "Bossmonster"},
				{"DemoModelsLayer.ModelsNames.Cyclops", "Cyclops"},
				{"DemoModelsLayer.ModelsNames.Monster", "Monster"},
				{"DemoModelsLayer.ModelsNames.Radiomonster", "Radiomonster"},
				{"DemoModelsLayer.ModelsNames.Smartmonster", "Smartmonster"},
				{"DemoModelsLayer.ModelsNames.Stereomonster", "Stereomonster"},
				{"DemoModelsLayer.ModelsNames.Telemonster", "Telemonster"},
				{"DemoModelsLayer.ModelsNames.Threeclopes", "Threeclopes"},
				{"DemoModelsLayer.ModelsNames.Robot_1", "Robot 1"},
				{"DemoModelsLayer.ModelsNames.Robot_2", "Robot 2"},
				{"DemoModelsLayer.ModelsNames.Robot_3", "Robot 3"},
				{"DemoModelsLayer.ModelsNames.Robot_4", "Robot 4"},
				{"DemoModelsLayer.ModelsNames.RollerRobot", "Roller Robot"},
				{"DemoModelsLayer.ModelsNames.Crystal", "Crystal"},
				{"DemoModelsLayer.ModelsNames.Hexanom", "Hexanom"},
				{"DemoModelsLayer.ModelsNames.Neutron", "Neutron"},
				{"DemoModelsLayer.ModelsNames.Prism", "Prism"},
				{"DemoModelsLayer.ModelsNames.Spring", "Spring"},
				{"DemoModelsLayer.ModelsNames.VectorTower", "Vector Tower"},
				{"DemoModelsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
				{"DemoModelsLayer.ModelsNames.FortRoyal", "Fort Royal"},
				{"DemoModelsLayer.ModelsNames.Skyscraper", "Skyscraper"},
				{"DemoModelsLayer.ModelsNames.Destroyer", "Destroyer"},
				{"DemoModelsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
				{"DemoModelsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
				{"DemoModelsLayer.ModelsNames.SpacePike", "Space Pike"},
				{"DemoModelsLayer.ModelsNames.TSpace", "TSpace"},
				{"DemoModelsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
				{"DemoModelsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
				{"DemoModelsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
				{"DemoModelsLayer.ModelsNames.Seesaw", "Seesaw"},
				{"DemoModelsLayer.ModelsNames.Slide", "Slide"},
				{"DemoModelsLayer.ModelsNames.Swing", "Swing"},
				{"DemoModelsLayer.ModelsNames.Frusaur", "Frusaur"},
				{"DemoModelsLayer.ModelsNames.Catamaran", "Catamaran"},
				{"DemoModelsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
				{"DemoModelsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
				{"DemoModelsLayer.ModelsNames.Airplane", "Airplane"},
				{"DemoModelsLayer.ModelsNames.ControlTower", "Control Tower"},
				{"DemoModelsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
				{"DemoModelsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
				{"DemoModelsLayer.ModelsNames.SpaceRadar", "Space Radar"},
				{"DemoModelsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
				{"DemoModelsLayer.ModelsNames.Babycopter", "Babycopter"},
				{"DemoModelsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
				{"DemoModelsLayer.ModelsNames.Giraffe", "Giraffe"},
				{"DemoModelsLayer.ModelsNames.HandBridge", "Hand-bridge"},
				{"DemoModelsLayer.ModelsNames.Plane", "Plane"},
				{"DemoModelsLayer.ModelsNames.Robot", "Robot"},
				{"DemoModelsLayer.ModelsNames.Tower", "Tower"},
				{"DemoModelsLayer.ModelsNames.Umberflower", "Umberflower"},
				{"DemoModelsLayer.ModelsNames.BabyPanda", "Baby Panda"},
				{"DemoModelsLayer.ModelsNames.Doggie", "Doggie"},
				{"DemoModelsLayer.ModelsNames.Lamb", "Lamb"},
				{"DemoModelsLayer.ModelsNames.Dandelion", "Dandelion"},
				{"DemoModelsLayer.ModelsNames.Lily", "Lily"},
				{"DemoModelsLayer.ModelsNames.BabyDeer", "Baby Deer"},
				{"DemoModelsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
				{"DemoModelsLayer.ModelsNames.Birdy", "Birdy"},
				{"DemoModelsLayer.ModelsNames.Lama", "Lama"},
				{"DemoModelsLayer.ModelsNames.LittleShip", "Little Ship"},
				{"DemoModelsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
				{"DemoModelsLayer.ModelsNames.Swallowtail", "Swallowtail"},
				{"DemoModelsLayer.ModelsNames.Moustashed", "Moustashed"},
				{"DemoModelsLayer.ModelsNames.QuadBike", "Quad Bike"},
				{"DemoModelsLayer.ModelsNames.RaceCar", "Race Car"},
				{"DemoModelsLayer.ModelsNames.Buggy", "Buggy"},
				{"DemoModelsLayer.ModelsNames.Motocycle", "Motocycle"},
				{"DemoModelsLayer.ModelsNames.Tricycle", "Tricycle"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 3"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 4"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 5"},
				{"DemoModelsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
				{"DemoModelsLayer.ModelsNames.Unbreakable", "Unbreakable"},
				{"DemoModelsLayer.ModelsNames.F", "F"},
			},
			new Dictionary<string, string>
			{
				{"EditorLayer.ActiveColor", "Kolory"},
				{"EditorLayer.Details", "Elementy"},

				{"Menu.Menu", "Menu"},
				{"Menu.NewScene", "Nowy projekt"},
				{"Menu.Save", "Zapisz..."},
				{"Menu.Load", "Wczytaj..."},
				{"Menu.Export", "Eksportuj..."},
				{"Menu.SceneInfo", "Szczegóły projektu"},
				{"Menu.Demo", "Demo"},
				{"Menu.Help", "Pomoc"},
				{"Menu.Exit", "Wyjście"},

				{"ModeSwitcher.Editor", "Tryb edycji"},
				{"ModeSwitcher.Instructions", "Tryb instrukcji"},

				{"SceneInfoLayer.Copy", "Kopiuj"},
				{"SceneInfoLayer.Height", "Wysokość:"},
				{"SceneInfoLayer.Length", "Długość:"},
				{"SceneInfoLayer.Width", "Szerokość:"},
				{"SceneInfoLayer.Weight", "Waga:"},
				{"SceneInfoLayer.TotalDetails", "Wszystkich elementów:"},
				{"SceneInfoLayer.cm", "cm"},
				{"SceneInfoLayer.gram", "g"},

				{"SceneInfoLayer.Black", "Czarny"},
				{"SceneInfoLayer.Blue", "Niebieski"},
				{"SceneInfoLayer.Brown", "Brązowy"},
				{"SceneInfoLayer.Gray", "Szary"},
				{"SceneInfoLayer.Green", "Zielony"},
				{"SceneInfoLayer.Red", "Czerwony"},
				{"SceneInfoLayer.White", "Biały"},
				{"SceneInfoLayer.Yellow", "Żółty"},

				{"SceneInfoLayer.BraceLineX2", "Łacznik wewnętrzny (2x1): "},
				{"SceneInfoLayer.BraceLineX3", "Łącznik wewnętrzny (3x1): "},
				{"SceneInfoLayer.BraceSquareX2", "Łącznik zewnętrzny (2x1): "},
				{"SceneInfoLayer.BraceSquareX3", "Łącznik zewnętrzny (3x1): "},
				{"SceneInfoLayer.Lego1x1", "Lego adapter 1x1: "},
				{"SceneInfoLayer.Lego2x1", "Lego adapter 2x1: "},
				{"SceneInfoLayer.Roll", "Zawias: "},
				{"SceneInfoLayer.RailX2", "Szyna: "},

				{"SceneInfoLayer.Axle1.0", "Oś 1.0: "},
				{"SceneInfoLayer.Axle2.0", "Oś 2.0: "},
				{"SceneInfoLayer.Axle2.5", "Oś 2.5: "},
				{"SceneInfoLayer.Axle3.0", "Oś 3.0: "},
				{"SceneInfoLayer.Axle3.5", "Oś 3.5: "},
				{"SceneInfoLayer.Axle8.0", "Oś 8.0: "},

                {"SceneInfoLayer.AxleBevelGear", "Przekładnia stożkowa: "},
                {"SceneInfoLayer.AxleCoupling", "Sprzęganie: "},
                {"SceneInfoLayer.AxleHub3x1", "Piasta (3x1): "},
                {"SceneInfoLayer.AxleHub5x1", "Piasta (5x1): "},
                {"SceneInfoLayer.AxleTip", "Wskazówka: "},
                {"SceneInfoLayer.AxleWasher", "Podkładka: "},
                {"SceneInfoLayer.AxleWasherToothed", "Podkładka zębata: "},
                {"SceneInfoLayer.AxleWheelBig", "Wielkie koło: "},
                {"SceneInfoLayer.AxleWheelSmall", "Małe koło: "},

				{"FileSelectionDialogLayer.SelectFile", "Wybierz projekt..."},
				{"FileSelectionDialogLayer.EnterName", "Nazwij projekt..."},
				{"FileSelectionDialogLayer.Up", "Do góry"},
				{"FileSelectionDialogLayer.Downloads", "Pobrane"},
				{"FileSelectionDialogLayer.Save", "Zapisz"},
				{"FileSelectionDialogLayer.Cancel", "Anuluj"},

				{"TutorialLayer.Next", "Dalej"},
				{"TutorialLayer.Welcome", "Witaj w\nFanclastic 3D Designer™!\n\nTen program umożliwi Ci projektowanie własnych budowli Fanclastic i generowanie do nich animowanych instrukcji oraz przeglądanie już istniejących projektów. \n\nwww.fanclastic.pl"},
				{"TutorialLayer.DetailsHint", "Aby dodać element do obecnego projektu, przeciągnij odpowiednią ikonę z panelu elementów na wybrane miejsce na planie."},
				{"TutorialLayer.SetFocusHint", "Aby zmienić punkt widzenia kamery, kliknij przycisk ustawienia ostrości, a następnie na dowolny element lub punkt na planie."},
				{"TutorialLayer.ChangeColorHint", "Użyj przycisku wyboru koloru, aby zmienić barwę dla użytych elementów."},
				{"TutorialLayer.RotateHint", "Aby obrócić wybrany element, użyj przycisków obrotu, każdy z nich obraca elementy wokół danej osi odpowiedniego koloru."},
				{"TutorialLayer.DeleteHint", "Użyj tego przycisku, aby usunąć wybrane elementy z planu."},
				{"TutorialLayer.ZoomHint.Base", "Użyj  {0} aby powiększyć i pomniejszyć zbliżenie kamery."},
				{"TutorialLayer.ZoomHint.Wheel", "kółka w myszce"},
				{"TutorialLayer.ZoomHint.Pinch", "uszczypnięcia"},
				{"TutorialLayer.LinkedSelection", "Kliknij i przytrzymaj element, aby zobaczyć wszystkie połączone części i obrócić budowlę przyciskami obrotu."},

				{"DemoModelsLayer.SetsNames.BigFigures", "Big Figures"},
				{"DemoModelsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
				{"DemoModelsLayer.SetsNames.Architectics", "Architectics"},
				{"DemoModelsLayer.SetsNames.Geometrics", "Geometrics"},
				{"DemoModelsLayer.SetsNames.Blasterology", "Blasterology"},
				{"DemoModelsLayer.SetsNames.Militarics", "Militarics"},
				{"DemoModelsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
				{"DemoModelsLayer.SetsNames.Monsterology", "Monsterology"},
				{"DemoModelsLayer.SetsNames.Robotology", "Robotology"},
				{"DemoModelsLayer.SetsNames.Geometry", "Geometry"},
				{"DemoModelsLayer.SetsNames.Architecture", "Architecture"},
				{"DemoModelsLayer.SetsNames.Spaceships", "Spaceships"},
				{"DemoModelsLayer.SetsNames.Playground", "Playground"},
				{"DemoModelsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
				{"DemoModelsLayer.SetsNames.Marine", "Marine"},
				{"DemoModelsLayer.SetsNames.Aircraft", "Aircraft"},
				{"DemoModelsLayer.SetsNames.Space", "Space"},
				{"DemoModelsLayer.SetsNames.Mix", "Mix"},
				{"DemoModelsLayer.SetsNames.Animals", "Animals"},
				{"DemoModelsLayer.SetsNames.Flowers", "Flowers"},
				{"DemoModelsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
				{"DemoModelsLayer.SetsNames.BirdLama", "Bird-Lama"},
				{"DemoModelsLayer.SetsNames.PlaneShip", "Plane-Ship"},
				{"DemoModelsLayer.SetsNames.Butterflies", "Butterflies"},
				{"DemoModelsLayer.SetsNames.Masks", "Masks"},
				{"DemoModelsLayer.SetsNames.Racing", "Racing"},
				{"DemoModelsLayer.SetsNames.RallyRade", "Rally Rade"},

				{"DemoModelsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
				{"DemoModelsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
				{"DemoModelsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
				{"DemoModelsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
				{"DemoModelsLayer.ModelsNames.KingsCastle", "King's Castle"},
				{"DemoModelsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
				{"DemoModelsLayer.ModelsNames.SpaceLight", "Space Light"},
				{"DemoModelsLayer.ModelsNames.Cube", "Cube"},
				{"DemoModelsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
				{"DemoModelsLayer.ModelsNames.Fractal", "Fractal"},
				{"DemoModelsLayer.ModelsNames.Globe", "Globe"},
				{"DemoModelsLayer.ModelsNames.Lattice", "Lattice"},
				{"DemoModelsLayer.ModelsNames.Pyramid", "Pyramid"},
				{"DemoModelsLayer.ModelsNames.Sphere", "Sphere"},
				{"DemoModelsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
				{"DemoModelsLayer.ModelsNames.Megablaster", "Megablaster"},
				{"DemoModelsLayer.ModelsNames.Miniblaster", "Miniblaster"},
				{"DemoModelsLayer.ModelsNames.Parablaster", "Parablaster"},
				{"DemoModelsLayer.ModelsNames.Fighter", "Fighter"},
				{"DemoModelsLayer.ModelsNames.Helicopter", "Helicopter"},
				{"DemoModelsLayer.ModelsNames.Submarine", "Submarine"},
				{"DemoModelsLayer.ModelsNames.Tank", "Tank"},
				{"DemoModelsLayer.ModelsNames.Dachshund", "Dachshund"},
				{"DemoModelsLayer.ModelsNames.Fawn", "Fawn"},
				{"DemoModelsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
				{"DemoModelsLayer.ModelsNames.SaurKing", "Saur King"},
				{"DemoModelsLayer.ModelsNames.Tortilla", "Tortilla"},
				{"DemoModelsLayer.ModelsNames.Triceratops", "Triceratops"},
				{"DemoModelsLayer.ModelsNames.Bossmonster", "Bossmonster"},
				{"DemoModelsLayer.ModelsNames.Cyclops", "Cyclops"},
				{"DemoModelsLayer.ModelsNames.Monster", "Monster"},
				{"DemoModelsLayer.ModelsNames.Radiomonster", "Radiomonster"},
				{"DemoModelsLayer.ModelsNames.Smartmonster", "Smartmonster"},
				{"DemoModelsLayer.ModelsNames.Stereomonster", "Stereomonster"},
				{"DemoModelsLayer.ModelsNames.Telemonster", "Telemonster"},
				{"DemoModelsLayer.ModelsNames.Threeclopes", "Threeclopes"},
				{"DemoModelsLayer.ModelsNames.Robot_1", "Robot 1"},
				{"DemoModelsLayer.ModelsNames.Robot_2", "Robot 2"},
				{"DemoModelsLayer.ModelsNames.Robot_3", "Robot 3"},
				{"DemoModelsLayer.ModelsNames.Robot_4", "Robot 4"},
				{"DemoModelsLayer.ModelsNames.RollerRobot", "Roller Robot"},
				{"DemoModelsLayer.ModelsNames.Crystal", "Crystal"},
				{"DemoModelsLayer.ModelsNames.Hexanom", "Hexanom"},
				{"DemoModelsLayer.ModelsNames.Neutron", "Neutron"},
				{"DemoModelsLayer.ModelsNames.Prism", "Prism"},
				{"DemoModelsLayer.ModelsNames.Spring", "Spring"},
				{"DemoModelsLayer.ModelsNames.VectorTower", "Vector Tower"},
				{"DemoModelsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
				{"DemoModelsLayer.ModelsNames.FortRoyal", "Fort Royal"},
				{"DemoModelsLayer.ModelsNames.Skyscraper", "Skyscraper"},
				{"DemoModelsLayer.ModelsNames.Destroyer", "Destroyer"},
				{"DemoModelsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
				{"DemoModelsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
				{"DemoModelsLayer.ModelsNames.SpacePike", "Space Pike"},
				{"DemoModelsLayer.ModelsNames.TSpace", "TSpace"},
				{"DemoModelsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
				{"DemoModelsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
				{"DemoModelsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
				{"DemoModelsLayer.ModelsNames.Seesaw", "Seesaw"},
				{"DemoModelsLayer.ModelsNames.Slide", "Slide"},
				{"DemoModelsLayer.ModelsNames.Swing", "Swing"},
				{"DemoModelsLayer.ModelsNames.Frusaur", "Frusaur"},
				{"DemoModelsLayer.ModelsNames.Catamaran", "Catamaran"},
				{"DemoModelsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
				{"DemoModelsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
				{"DemoModelsLayer.ModelsNames.Airplane", "Airplane"},
				{"DemoModelsLayer.ModelsNames.ControlTower", "Control Tower"},
				{"DemoModelsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
				{"DemoModelsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
				{"DemoModelsLayer.ModelsNames.SpaceRadar", "Space Radar"},
				{"DemoModelsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
				{"DemoModelsLayer.ModelsNames.Babycopter", "Babycopter"},
				{"DemoModelsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
				{"DemoModelsLayer.ModelsNames.Giraffe", "Giraffe"},
				{"DemoModelsLayer.ModelsNames.HandBridge", "Hand-bridge"},
				{"DemoModelsLayer.ModelsNames.Plane", "Plane"},
				{"DemoModelsLayer.ModelsNames.Robot", "Robot"},
				{"DemoModelsLayer.ModelsNames.Tower", "Tower"},
				{"DemoModelsLayer.ModelsNames.Umberflower", "Umberflower"},
				{"DemoModelsLayer.ModelsNames.BabyPanda", "Baby Panda"},
				{"DemoModelsLayer.ModelsNames.Doggie", "Doggie"},
				{"DemoModelsLayer.ModelsNames.Lamb", "Lamb"},
				{"DemoModelsLayer.ModelsNames.Dandelion", "Dandelion"},
				{"DemoModelsLayer.ModelsNames.Lily", "Lily"},
				{"DemoModelsLayer.ModelsNames.BabyDeer", "Baby Deer"},
				{"DemoModelsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
				{"DemoModelsLayer.ModelsNames.Birdy", "Birdy"},
				{"DemoModelsLayer.ModelsNames.Lama", "Lama"},
				{"DemoModelsLayer.ModelsNames.LittleShip", "Little Ship"},
				{"DemoModelsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
				{"DemoModelsLayer.ModelsNames.Swallowtail", "Swallowtail"},
				{"DemoModelsLayer.ModelsNames.Moustashed", "Moustashed"},
				{"DemoModelsLayer.ModelsNames.QuadBike", "Quad Bike"},
				{"DemoModelsLayer.ModelsNames.RaceCar", "Race Car"},
				{"DemoModelsLayer.ModelsNames.Buggy", "Buggy"},
				{"DemoModelsLayer.ModelsNames.Motocycle", "Motocycle"},
				{"DemoModelsLayer.ModelsNames.Tricycle", "Tricycle"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 3"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 4"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 5"},
				{"DemoModelsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
				{"DemoModelsLayer.ModelsNames.Unbreakable", "Unbreakable"},
				{"DemoModelsLayer.ModelsNames.F", "F"},
			},
			new Dictionary<string, string>
			{
				{"EditorLayer.ActiveColor", "גוון פעיל"},
				{"EditorLayer.Details", "רכיבים"},

				{"Menu.Menu", "תפריט"},
				{"Menu.NewScene", "פעולה חדשה"},
				{"Menu.Save", "שמירה..."},
				{"Menu.Load", "פתיחת קובץ..."},
				{"Menu.Export", "ייצוא..."},
				{"Menu.SceneInfo", "מידת הזירה"},
				{"Menu.Demo", "מודלים לדוגמה"},
				{"Menu.Help", "עזרה"},
				{"Menu.Exit", "יציאה"},

                {"ModeSwitcher.Editor", "עריכה"},
				{"ModeSwitcher.Instructions", "הוראות"},

				{"SceneInfoLayer.Copy", "העתק"},
				{"SceneInfoLayer.Height", "גובה"},
				{"SceneInfoLayer.Length", "אורך"},
				{"SceneInfoLayer.Width", "עובי"},
				{"SceneInfoLayer.Weight", "משקל"},
				{"SceneInfoLayer.TotalDetails", "סה\"כ רכיבים"},
				{"SceneInfoLayer.cm", "ס\"מ"},
				{"SceneInfoLayer.gram", "גרם"},

				{"SceneInfoLayer.Black", "שחור"},
				{"SceneInfoLayer.Blue", "כחול"},
				{"SceneInfoLayer.Brown", "חום"},
				{"SceneInfoLayer.Gray", "אפור"},
				{"SceneInfoLayer.Green", "ירוק"},
				{"SceneInfoLayer.Red", "אדום"},
				{"SceneInfoLayer.White", "לבן"},
				{"SceneInfoLayer.Yellow", "צהוב"},

				{"SceneInfoLayer.BraceLineX2","סוגר מסולסל" + " (2x1) "},
				{"SceneInfoLayer.BraceLineX3", "סוגר מסולסל" + " (3x1) "},
				{"SceneInfoLayer.BraceSquareX2", "סוגר מלבני" + " (2x1) "},
				{"SceneInfoLayer.BraceSquareX3", "סוגר מלבני" + " (3x1) "},
				{"SceneInfoLayer.Lego1x1", "לגו" + " 1x1 "},
				{"SceneInfoLayer.Lego2x1", "לגו" + " 2x1 "},
				{"SceneInfoLayer.Roll", "רול "},
				{"SceneInfoLayer.RailX2", "מסילה "},

				{"SceneInfoLayer.Axle1.0", "סרן" + " 1.0 "},
				{"SceneInfoLayer.Axle2.0", "סרן" + " 2.0 "},
				{"SceneInfoLayer.Axle2.5", "סרן" + " 2.5 "},
				{"SceneInfoLayer.Axle3.0", "סרן" + " 3.0 "},
				{"SceneInfoLayer.Axle3.5", "סרן" + " 3.5 "},
				{"SceneInfoLayer.Axle8.0", "סרן" + " 8.0 "},

                {"SceneInfoLayer.AxleBevelGear", "ציוד שפוע "},
                {"SceneInfoLayer.AxleCoupling", "מצמד "},
                {"SceneInfoLayer.AxleHub3x1", "רכזת" + " (3x1) "},
                {"SceneInfoLayer.AxleHub5x1", "רכזת" + " (5x1) "},
                {"SceneInfoLayer.AxleTip", "חוֹד "},
                {"SceneInfoLayer.AxleWasher", "דיסקוס "},
                {"SceneInfoLayer.AxleWasherToothed", "דיסקוס מחורץ "},
                {"SceneInfoLayer.AxleWheelBig", "גלגל גדול "},
                {"SceneInfoLayer.AxleWheelSmall", "גלגל קטן "},

				{"FileSelectionDialogLayer.SelectFile", "בחר קובץ..."},
				{"FileSelectionDialogLayer.EnterName", "הזן שם..."},
				{"FileSelectionDialogLayer.Up", "למעלה"},
				{"FileSelectionDialogLayer.Downloads", "הורדות"},
				{"FileSelectionDialogLayer.Save", "שמירה"},
				{"FileSelectionDialogLayer.Cancel", "ביטול"},

				{"TutorialLayer.Next", "הבא"},
				{"TutorialLayer.Welcome", "ברוכים הבאים ל\nFanclastic 3D Designer!\n\nתוכנית זו מסייעת לך לבנות מודלים ,להציג הוראות הרכבה וליצור מודלים משלך."},
				{"TutorialLayer.DetailsHint", "כדי לזירה, גרור את הסמל המתאים מהלוח רכיבים לזירה."},
				{"TutorialLayer.SetFocusHint", "לשינוי נקודת עיגון המצלמה לחצו על לחצן הגדרת המוקד ולאחר מכן על כל רכיב או מקום בזירה."},
				{"TutorialLayer.ChangeColorHint", "השתמש בלחצן בחירת צבע על מנת להגדיר צבע עבור הרכיבים שנבחרו."},
				{"TutorialLayer.RotateHint", "כדי לסובב את הרכיבים הנבחרים, השתמש בלחצני הסיבוב. כל לחצן הצבוע בצבע אחר מסובב את הרכיב בכיוון שונה."},
				{"TutorialLayer.DeleteHint", "השתמש בלחצן זה כדי למחוק את הרכיבים הנבחרים מהזירה."},
			
                {"TutorialLayer.ZoomHint.Base", "כדי לקרב ולהרחיק את המצלמה השתמש" + " {0}."},
                {"TutorialLayer.ZoomHint.Wheel", "השתמש בגלגל של עכבר"},
				{"TutorialLayer.ZoomHint.Pinch", "באצבעות"},
				{"TutorialLayer.LinkedSelection", "הלחץ על רכיב והחזק כדי לבחור את כל החלקים הקשורים אליו."},

				{"DemoModelsLayer.SetsNames.BigFigures", "Big Figures"},
				{"DemoModelsLayer.SetsNames.Cosmoclastics", "Cosmoclastics"},
				{"DemoModelsLayer.SetsNames.Architectics", "Architectics"},
				{"DemoModelsLayer.SetsNames.Geometrics", "Geometrics"},
				{"DemoModelsLayer.SetsNames.Blasterology", "Blasterology"},
				{"DemoModelsLayer.SetsNames.Militarics", "Militarics"},
				{"DemoModelsLayer.SetsNames.Zoosaurics", "Zoosaurics"},
				{"DemoModelsLayer.SetsNames.Monsterology", "Monsterology"},
				{"DemoModelsLayer.SetsNames.Robotology", "Robotology"},
				{"DemoModelsLayer.SetsNames.Geometry", "Geometry"},
				{"DemoModelsLayer.SetsNames.Architecture", "Architecture"},
				{"DemoModelsLayer.SetsNames.Spaceships", "Spaceships"},
				{"DemoModelsLayer.SetsNames.Playground", "Playground"},
				{"DemoModelsLayer.SetsNames.Dinosaurs", "Dinosaurs"},
				{"DemoModelsLayer.SetsNames.Marine", "Marine"},
				{"DemoModelsLayer.SetsNames.Aircraft", "Aircraft"},
				{"DemoModelsLayer.SetsNames.Space", "Space"},
				{"DemoModelsLayer.SetsNames.Mix", "Mix"},
				{"DemoModelsLayer.SetsNames.Animals", "Animals"},
				{"DemoModelsLayer.SetsNames.Flowers", "Flowers"},
				{"DemoModelsLayer.SetsNames.DeerGiraff", "Deer-Giraff"},
				{"DemoModelsLayer.SetsNames.BirdLama", "Bird-Lama"},
				{"DemoModelsLayer.SetsNames.PlaneShip", "Plane-Ship"},
				{"DemoModelsLayer.SetsNames.Butterflies", "Butterflies"},
				{"DemoModelsLayer.SetsNames.Masks", "Masks"},
				{"DemoModelsLayer.SetsNames.Racing", "Racing"},
				{"DemoModelsLayer.SetsNames.RallyRade", "Rally Rade"},

				{"DemoModelsLayer.ModelsNames.GiraffeGulliver", "Giraffe Gulliver"},
				{"DemoModelsLayer.ModelsNames.DeltaSpaceship", "Delta Spaceship"},
				{"DemoModelsLayer.ModelsNames.InfinitySpaceship", "Infinity Spaceship"},
				{"DemoModelsLayer.ModelsNames.OmegaSpaceship", "Omega Spaceship"},
				{"DemoModelsLayer.ModelsNames.KingsCastle", "King's Castle"},
				{"DemoModelsLayer.ModelsNames.SkySpearTower", "Sky Spear Tower"},
				{"DemoModelsLayer.ModelsNames.SpaceLight", "Space Light"},
				{"DemoModelsLayer.ModelsNames.Cube", "Cube"},
				{"DemoModelsLayer.ModelsNames.FlexibleStick", "Flexible Stick"},
				{"DemoModelsLayer.ModelsNames.Fractal", "Fractal"},
				{"DemoModelsLayer.ModelsNames.Globe", "Globe"},
				{"DemoModelsLayer.ModelsNames.Lattice", "Lattice"},
				{"DemoModelsLayer.ModelsNames.Pyramid", "Pyramid"},
				{"DemoModelsLayer.ModelsNames.Sphere", "Sphere"},
				{"DemoModelsLayer.ModelsNames.Hyperblaster", "Hyperblaster"},
				{"DemoModelsLayer.ModelsNames.Megablaster", "Megablaster"},
				{"DemoModelsLayer.ModelsNames.Miniblaster", "Miniblaster"},
				{"DemoModelsLayer.ModelsNames.Parablaster", "Parablaster"},
				{"DemoModelsLayer.ModelsNames.Fighter", "Fighter"},
				{"DemoModelsLayer.ModelsNames.Helicopter", "Helicopter"},
				{"DemoModelsLayer.ModelsNames.Submarine", "Submarine"},
				{"DemoModelsLayer.ModelsNames.Tank", "Tank"},
				{"DemoModelsLayer.ModelsNames.Dachshund", "Dachshund"},
				{"DemoModelsLayer.ModelsNames.Fawn", "Fawn"},
				{"DemoModelsLayer.ModelsNames.GiraffeKid", "Giraffe Kid"},
				{"DemoModelsLayer.ModelsNames.SaurKing", "Saur King"},
				{"DemoModelsLayer.ModelsNames.Tortilla", "Tortilla"},
				{"DemoModelsLayer.ModelsNames.Triceratops", "Triceratops"},
				{"DemoModelsLayer.ModelsNames.Bossmonster", "Bossmonster"},
				{"DemoModelsLayer.ModelsNames.Cyclops", "Cyclops"},
				{"DemoModelsLayer.ModelsNames.Monster", "Monster"},
				{"DemoModelsLayer.ModelsNames.Radiomonster", "Radiomonster"},
				{"DemoModelsLayer.ModelsNames.Smartmonster", "Smartmonster"},
				{"DemoModelsLayer.ModelsNames.Stereomonster", "Stereomonster"},
				{"DemoModelsLayer.ModelsNames.Telemonster", "Telemonster"},
				{"DemoModelsLayer.ModelsNames.Threeclopes", "Threeclopes"},
				{"DemoModelsLayer.ModelsNames.Robot_1", "Robot 1"},
				{"DemoModelsLayer.ModelsNames.Robot_2", "Robot 2"},
				{"DemoModelsLayer.ModelsNames.Robot_3", "Robot 3"},
				{"DemoModelsLayer.ModelsNames.Robot_4", "Robot 4"},
				{"DemoModelsLayer.ModelsNames.RollerRobot", "Roller Robot"},
				{"DemoModelsLayer.ModelsNames.Crystal", "Crystal"},
				{"DemoModelsLayer.ModelsNames.Hexanom", "Hexanom"},
				{"DemoModelsLayer.ModelsNames.Neutron", "Neutron"},
				{"DemoModelsLayer.ModelsNames.Prism", "Prism"},
				{"DemoModelsLayer.ModelsNames.Spring", "Spring"},
				{"DemoModelsLayer.ModelsNames.VectorTower", "Vector Tower"},
				{"DemoModelsLayer.ModelsNames.ArrowTower", "Arrow Tower"},
				{"DemoModelsLayer.ModelsNames.FortRoyal", "Fort Royal"},
				{"DemoModelsLayer.ModelsNames.Skyscraper", "Skyscraper"},
				{"DemoModelsLayer.ModelsNames.Destroyer", "Destroyer"},
				{"DemoModelsLayer.ModelsNames.GlitchSender", "Glitch Sender"},
				{"DemoModelsLayer.ModelsNames.SpaceIntruder", "Space Intruder"},
				{"DemoModelsLayer.ModelsNames.SpacePike", "Space Pike"},
				{"DemoModelsLayer.ModelsNames.TSpace", "TSpace"},
				{"DemoModelsLayer.ModelsNames.CarouselTower", "Carousel Tower"},
				{"DemoModelsLayer.ModelsNames.JumpingBalance", "Jumping Balance"},
				{"DemoModelsLayer.ModelsNames.MerryGoRound", "Merry Go Round"},
				{"DemoModelsLayer.ModelsNames.Seesaw", "Seesaw"},
				{"DemoModelsLayer.ModelsNames.Slide", "Slide"},
				{"DemoModelsLayer.ModelsNames.Swing", "Swing"},
				{"DemoModelsLayer.ModelsNames.Frusaur", "Frusaur"},
				{"DemoModelsLayer.ModelsNames.Catamaran", "Catamaran"},
				{"DemoModelsLayer.ModelsNames.FairWindShip", "Fair Wind Ship"},
				{"DemoModelsLayer.ModelsNames.SeaLightTower", "Sea Light Tower"},
				{"DemoModelsLayer.ModelsNames.Airplane", "Airplane"},
				{"DemoModelsLayer.ModelsNames.ControlTower", "Control Tower"},
				{"DemoModelsLayer.ModelsNames.FieryRocket", "Fiery Rocket"},
				{"DemoModelsLayer.ModelsNames.GammaRayDestroyer", "Gamma Ray Destroyer"},
				{"DemoModelsLayer.ModelsNames.SpaceRadar", "Space Radar"},
				{"DemoModelsLayer.ModelsNames.StrikeFighterVolcano", "Strike Fighter Volcano"},
				{"DemoModelsLayer.ModelsNames.Babycopter", "Babycopter"},
				{"DemoModelsLayer.ModelsNames.DragonflyPlane", "Dragonfly-Plane"},
				{"DemoModelsLayer.ModelsNames.Giraffe", "Giraffe"},
				{"DemoModelsLayer.ModelsNames.HandBridge", "Hand-bridge"},
				{"DemoModelsLayer.ModelsNames.Plane", "Plane"},
				{"DemoModelsLayer.ModelsNames.Robot", "Robot"},
				{"DemoModelsLayer.ModelsNames.Tower", "Tower"},
				{"DemoModelsLayer.ModelsNames.Umberflower", "Umberflower"},
				{"DemoModelsLayer.ModelsNames.BabyPanda", "Baby Panda"},
				{"DemoModelsLayer.ModelsNames.Doggie", "Doggie"},
				{"DemoModelsLayer.ModelsNames.Lamb", "Lamb"},
				{"DemoModelsLayer.ModelsNames.Dandelion", "Dandelion"},
				{"DemoModelsLayer.ModelsNames.Lily", "Lily"},
				{"DemoModelsLayer.ModelsNames.BabyDeer", "Baby Deer"},
				{"DemoModelsLayer.ModelsNames.BabyGiraffe", "Baby Giraffe"},
				{"DemoModelsLayer.ModelsNames.Birdy", "Birdy"},
				{"DemoModelsLayer.ModelsNames.Lama", "Lama"},
				{"DemoModelsLayer.ModelsNames.LittleShip", "Little Ship"},
				{"DemoModelsLayer.ModelsNames.Hawkmoth", "Hawkmoth"},
				{"DemoModelsLayer.ModelsNames.Swallowtail", "Swallowtail"},
				{"DemoModelsLayer.ModelsNames.Moustashed", "Moustashed"},
				{"DemoModelsLayer.ModelsNames.QuadBike", "Quad Bike"},
				{"DemoModelsLayer.ModelsNames.RaceCar", "Race Car"},
				{"DemoModelsLayer.ModelsNames.Buggy", "Buggy"},
				{"DemoModelsLayer.ModelsNames.Motocycle", "Motocycle"},
				{"DemoModelsLayer.ModelsNames.Tricycle", "Tricycle"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(1)", "Lattice 3x3 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_3x3(2)", "Lattice 3x3 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(1)", "Lattice 6x2 1"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(2)", "Lattice 6x2 2"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(3)", "Lattice 6x2 3"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(4)", "Lattice 6x2 4"},
				{"DemoModelsLayer.ModelsNames.Lattice_6x2(5)", "Lattice 6x2 5"},
				{"DemoModelsLayer.ModelsNames.Tetrahedron", "Tetrahedron"},
				{"DemoModelsLayer.ModelsNames.Unbreakable", "Unbreakable"},
				{"DemoModelsLayer.ModelsNames.F", "F"},
			}
		};

        public static int Lang
        {
            get
            {
                if (_lang != -1)
                {
                    return _lang;
                }

                if (!PlayerPrefs.HasKey("Language"))
                {
                    int defaultLang;

                    switch (Application.systemLanguage)
                    {
                        case SystemLanguage.Russian:
                            defaultLang = 1;
                            break;
                        case SystemLanguage.German:
                            defaultLang = 2;
                            break;
                        case SystemLanguage.Polish:
                            defaultLang = 3;
                            break;
                        case SystemLanguage.Hebrew:
                            defaultLang = 4;
                            break;
                        default:
                            defaultLang = 0;
                            break;
                    }

                    PlayerPrefs.SetInt("Language", defaultLang);
                }

                _lang = PlayerPrefs.GetInt("Language");

                return _lang;
            }

            set
            {
                _lang = value;
                PlayerPrefs.SetInt("Language", value);
            }
        }
        private static int _lang = -1;

        public string TextKey;

        private Text _text;
        private bool _updateOnEnable; // чтобы RTL тексты отображались правильно, 
        // их нужно передавать только в активные текстовые компоненты

        public void Awake()
        {
            AppController.Instance.LanguageChanged += SetLanguage;
        }

        public void Start()
        {
            SetLanguage(Lang);
        }

        protected void OnEnable()
        {
            if (!_updateOnEnable)
            {
                return;
            }

            SetLanguage(Lang);
            _updateOnEnable = false;
        }

        public void SetLanguage(int index)
        {
            if (_text == null)
            {

                _text = GetComponent<Text>();

                if (_text == null)
                {
                    Debug.LogError("Text component not found: " + gameObject.name);
                    return;
                }
            }

            if (!isActiveAndEnabled)
            {
                _updateOnEnable = true;
                return;
            }

            string newText;

            if (!Dictionaries[index].TryGetValue(TextKey, out newText))
            {
                Debug.LogError("Key " + TextKey + " not found in dictionary " + index);
                return;
            }

            _text.TextRespectingRtl(newText);
        }
    }
}
